/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import * as zod from 'zod';


/**
 * Get all scouting fields for a season. Takes season uuid and the field type.
 *
 * Parameters:
 *     season_uuid (`UUID`): The UUID of the season to get fields for
 *     scouting_type (`ScoutingType`): The scouting type to get fields for
 *
 * Returns:
 *     list[MatchScoutingFieldResponse | PitScoutingFieldResponse]: A list of all scouting fields for the season
 * @summary Get Season Fields
 */
export const GetSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetParams = zod.object({
  "season_uuid": zod.uuid(),
  "scouting_type": zod.enum(['match', 'pit'])
})

export const GetSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponseItem = zod.union([zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})])
export const GetSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse = zod.array(GetSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponseItem)

/**
 * Archive all scouting fields for a season
 *
 * Requires superuser access
 *
 * Parameters:
 *     season_uuid (`UUID`): The UUID of the season to archive fields for
 *     scouting_type (`ScoutingType`): The scouting type to archive fields for
 *
 * Returns:
 *     `MessageResponse`: A message indicating that the fields were archived
 * @summary Archive Season Fields
 */
export const ArchiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteParams = zod.object({
  "season_uuid": zod.uuid(),
  "scouting_type": zod.enum(['match', 'pit'])
})

export const ArchiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * Create a new scouting field
 *
 * Parameters:
 *     data (`MatchScoutingFieldRequest | PitScoutingFieldRequest`): The data to create the field with
 *
 * Returns:
 *     `MatchScoutingFieldResponse | PitScoutingFieldResponse`: The created field
 *
 * TODO: Allow non-superusers to create organization fields
 * @summary Create Field
 */
export const CreateFieldFieldsCreatePostBody = zod.union([zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean()
})])

export const CreateFieldFieldsCreatePostResponse = zod.union([zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})])

/**
 * Edit a scouting field
 *
 * Parameters:
 *     data (`MatchScoutingFieldRequest | PitScoutingFieldRequest`): The data to edit the field
 *
 * Returns:
 *     `MatchScoutingFieldResponse | PitScoutingFieldResponse`: The edited field
 * @summary Edit Field
 */
export const EditFieldFieldsEditPatchBody = zod.union([zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean()
})])

export const EditFieldFieldsEditPatchResponse = zod.union([zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})])

/**
 * Get all scouting field presets
 *
 * Parameters:
 *     scouting_type (`ScoutingType`): The scouting type to get presets for
 *
 * Returns:
 *     `list[ScoutingFieldPresetResponse]`: A list of all scouting field presets
 * @summary Get Field Presets
 */
export const GetFieldPresetsFieldsPresetsScoutingTypeGetParams = zod.object({
  "scouting_type": zod.enum(['match', 'pit'])
})

export const GetFieldPresetsFieldsPresetsScoutingTypeGetResponseItem = zod.object({
  "name": zod.string(),
  "preset": zod.unknown()
})
export const GetFieldPresetsFieldsPresetsScoutingTypeGetResponse = zod.array(GetFieldPresetsFieldsPresetsScoutingTypeGetResponseItem)

/**
 * Archive a scouting field
 *
 * Requires superuser access
 *
 * Parameters:
 *     field_uuid (`UUID`): The UUID of the field to archive
 *
 * Returns:
 *     `MessageResponse`: A message indicating that the field was archived
 *
 * TODO: Allow non-superusers to archive organization fields that belong to their organization
 * @summary Archive Field
 */
export const ArchiveFieldFieldsArchiveFieldUuidDeleteParams = zod.object({
  "field_uuid": zod.uuid()
})

export const ArchiveFieldFieldsArchiveFieldUuidDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * Reorder scouting fields
 *
 * Based on the order of the fields in the request, the fields will be reordered to that order.
 * It is assumed that all fields in this request are meant to be reordered together. Only pass fields to this request that you want to reorder.
 * If fields have parents, the parents must be in the request as well. Order children on a different "level" than their parents, but in the order they appear in the list.
 *
 * Parameters:
 *     data (`list[MatchScoutingFieldRequest] | list[PitScoutingFieldRequest]`): The data to reorder the fields
 *
 * Returns:
 *     `list[MatchScoutingFieldResponse | PitScoutingFieldResponse]`: A list of all fields in the new order
 *
 * TODO: Allow non-superusers to reorder organization fields that belong to their organization
 * @summary Reorder Fields
 */
export const ReorderFieldsFieldsReorderPatchBody = zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.array(zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean()
}))])

export const ReorderFieldsFieldsReorderPatchResponseItem = zod.union([zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "parent_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("match"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "stat_type": zod.union([zod.enum(['section', 'auton_score', 'auton_miss', 'teleop_score', 'teleop_miss', 'capability', 'other', 'ignore']),zod.null()]),
  "game_piece_uuid": zod.union([zod.uuid(),zod.null()]),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.union([zod.uuid(),zod.null()]),
  "organization_uuid": zod.union([zod.uuid(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "scouting_type": zod.literal("pit"),
  "field_type": zod.enum(['section', 'string', 'large_number', 'small_number', 'coarse_small_number', 'boolean', 'choice', 'multiple_choice', 'number', 'image']),
  "required": zod.boolean(),
  "options": zod.union([zod.object({
  "uuid": zod.uuid(),
  "choices": zod.union([zod.array(zod.object({
  "uuid": zod.uuid(),
  "name": zod.string(),
  "simple_name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),zod.null()]),
  "default": zod.union([zod.int(),zod.null()]),
  "minimum": zod.union([zod.int(),zod.null()]),
  "maximum": zod.union([zod.int(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
}),zod.null()]),
  "order": zod.int(),
  "archived": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})])
export const ReorderFieldsFieldsReorderPatchResponse = zod.array(ReorderFieldsFieldsReorderPatchResponseItem)

