/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import * as zod from 'zod';


/**
 * Validates the current user, and returns their details

Returns:
    UserMeResponse: The current user details, and whether they are authenticated or not
 * @summary Me
 */
export const MeAuthMeGetResponse = zod.object({
  "authenticated": zod.boolean(),
  "user": zod.union([zod.object({
  "uuid": zod.string().uuid(),
  "username": zod.string(),
  "email": zod.string().email(),
  "is_superuser": zod.boolean(),
  "display_name": zod.string(),
  "team_number": zod.number(),
  "email_verified": zod.boolean(),
  "created_at": zod.string().datetime({"offset":true})
}),zod.null()])
})

/**
 * Logs in a user

Returns:
    MessageResponse: A message indicating that the user has been logged in
 * @summary Login
 */
export const LoginAuthLoginPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Create a new user

If this is the first user on the server, make them a superuser

Paramaters:
    data (SignupRequest): The data to create the user

Returns:
    MessageResponse: A message indicating that the user has been created
 * @summary Signup
 */
export const SignupAuthSignupPostBody = zod.object({
  "username": zod.string(),
  "email": zod.string().email(),
  "password": zod.string(),
  "confirm_password": zod.string(),
  "team_number": zod.number(),
  "display_name": zod.string()
})

export const SignupAuthSignupPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Logs out a user
 * @summary Logout
 */
export const LogoutAuthLogoutPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Get all users on the server

Requires superuser access

Returns:
    list[User]: A list of all users
 * @summary Get Users
 */
export const GetUsersUsersGetResponseItem = zod.object({
  "uuid": zod.string().uuid(),
  "username": zod.string(),
  "email": zod.string().email(),
  "is_superuser": zod.boolean(),
  "display_name": zod.string(),
  "team_number": zod.number(),
  "email_verified": zod.boolean(),
  "created_at": zod.string().datetime({"offset":true})
})
export const GetUsersUsersGetResponse = zod.array(GetUsersUsersGetResponseItem)

/**
 * Delete a user on the server

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to delete

Returns:
    MessageResponse: A message indicating that the user was deleted
 * @summary Delete User
 */
export const DeleteUserUsersDeleteUuidDeleteParams = zod.object({
  "uuid": zod.string().uuid()
})

export const DeleteUserUsersDeleteUuidDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * Get the settings for the current user

Returns:
    BaseSettings: The settings for the current user
 * @summary Get User Settings
 */
export const GetUserSettingsUsersMeGetSettingsGetResponse = zod.object({
  "favorite_events": zod.array(zod.string())
})

/**
 * Update the settings for the current user

Parameters:
    data (BaseSettings): The settings to update

Returns:
    BaseSettings: The settings for the current user
 * @summary Update User Settings
 */
export const UpdateUserSettingsUsersMeUpdateSettingsPostBody = zod.object({
  "favorite_events": zod.array(zod.string())
})

export const UpdateUserSettingsUsersMeUpdateSettingsPostResponse = zod.object({
  "favorite_events": zod.array(zod.string())
})

/**
 * Set a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to set as a superuser

Returns:
    User: The user that was set as a superuser
 * @summary Set Superuser
 */
export const SetSuperuserUsersSetSuperuserUuidPostParams = zod.object({
  "uuid": zod.string().uuid()
})

export const SetSuperuserUsersSetSuperuserUuidPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Remove a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to remove as a superuser

Returns:
    User: The user that was removed as a superuser
 * @summary Remove Superuser
 */
export const RemoveSuperuserUsersRemoveSuperuserUuidPostParams = zod.object({
  "uuid": zod.string().uuid()
})

export const RemoveSuperuserUsersRemoveSuperuserUuidPostResponse = zod.object({
  "message": zod.string()
})

