/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import * as zod from 'zod';


/**
 * Validates the current user, and returns their details

Returns:
    UserMeResponse: The current user details, and whether they are authenticated or not
 * @summary Me
 */
export const MeAuthMeGetResponse = zod.object({
  "authenticated": zod.boolean(),
  "user": zod.union([zod.object({
  "uuid": zod.string().uuid(),
  "username": zod.string(),
  "email": zod.string().email(),
  "is_superuser": zod.boolean(),
  "display_name": zod.union([zod.string(),zod.null()]),
  "team_number": zod.number(),
  "email_verified": zod.boolean(),
  "profile_picture_url": zod.union([zod.string(),zod.null()]),
  "created_at": zod.string().datetime({"offset":true})
}),zod.null()]),
  "settings": zod.union([zod.array(zod.object({
  "key": zod.string(),
  "value": zod.union([zod.unknown(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "section": zod.union([zod.string(),zod.null()]),
  "visible": zod.boolean(),
  "type": zod.enum(['string', 'number', 'boolean', 'array', 'json'])
})),zod.null()])
})

/**
 * Logs in a user

Returns:
    MessageResponse: A message indicating that the user has been logged in
 * @summary Login
 */
export const LoginAuthLoginPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Create a new user

If this is the first user on the server, make them a superuser

TODO: email_verified status probably shouldn't come from the client, and should instead be verified by the server to prevent verified spoofing

Paramaters:
    data (SignupRequest): The data to create the user

Returns:
    MessageResponse: A message indicating that the user has been created
 * @summary Signup
 */
export const SignupAuthSignupPostBody = zod.object({
  "username": zod.string(),
  "email": zod.string().email(),
  "password": zod.string(),
  "confirm_password": zod.string(),
  "team_number": zod.number(),
  "display_name": zod.string(),
  "email_verified": zod.boolean()
})

export const SignupAuthSignupPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Logs out a user
 * @summary Logout
 */
export const LogoutAuthLogoutPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Get all users on the server

Requires superuser access

Returns:
    list[User]: A list of all users
 * @summary Get Users
 */
export const GetUsersUsersGetResponseItem = zod.object({
  "uuid": zod.string().uuid(),
  "username": zod.string(),
  "email": zod.string().email(),
  "is_superuser": zod.boolean(),
  "display_name": zod.union([zod.string(),zod.null()]),
  "team_number": zod.number(),
  "email_verified": zod.boolean(),
  "profile_picture_url": zod.union([zod.string(),zod.null()]),
  "created_at": zod.string().datetime({"offset":true})
})
export const GetUsersUsersGetResponse = zod.array(GetUsersUsersGetResponseItem)

/**
 * Delete a user on the server

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to delete

Returns:
    MessageResponse: A message indicating that the user was deleted
 * @summary Delete User
 */
export const DeleteUserUsersDeleteUuidDeleteParams = zod.object({
  "uuid": zod.string().uuid()
})

export const DeleteUserUsersDeleteUuidDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * Get the settings for the current user

Returns:
    BaseSettings: The settings for the current user
 * @summary Get User Settings
 */
export const GetUserSettingsUsersMeGetSettingsGetResponseItem = zod.object({
  "key": zod.string(),
  "value": zod.union([zod.unknown(),zod.null()]),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "section": zod.union([zod.string(),zod.null()]),
  "visible": zod.boolean(),
  "type": zod.enum(['string', 'number', 'boolean', 'array', 'json'])
})
export const GetUserSettingsUsersMeGetSettingsGetResponse = zod.array(GetUserSettingsUsersMeGetSettingsGetResponseItem)

/**
 * Update the settings for the current user

Parameters:
    data (BaseSettings): The settings to update

Returns:
    BaseSettings: The settings for the current user
 * @summary Update User Settings
 */
export const UpdateUserSettingsUsersMeUpdateSettingsPostBody = zod.object({
  "favorite_events": zod.union([zod.array(zod.unknown()),zod.null()]).optional()
})

export const UpdateUserSettingsUsersMeUpdateSettingsPostResponse = zod.object({
  "favorite_events": zod.union([zod.array(zod.unknown()),zod.null()]).optional()
})

/**
 * Set a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to set as a superuser

Returns:
    User: The user that was set as a superuser
 * @summary Set Superuser
 */
export const SetSuperuserUsersSetSuperuserUuidPostParams = zod.object({
  "uuid": zod.string().uuid()
})

export const SetSuperuserUsersSetSuperuserUuidPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Remove a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to remove as a superuser

Returns:
    User: The user that was removed as a superuser
 * @summary Remove Superuser
 */
export const RemoveSuperuserUsersRemoveSuperuserUuidPostParams = zod.object({
  "uuid": zod.string().uuid()
})

export const RemoveSuperuserUsersRemoveSuperuserUuidPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Set the display name for the current user

Parameters:
    display_name (str): The display name to set

Returns:
    MessageResponse: A message indicating that the display name was set
 * @summary Set Display Name
 */
export const SetDisplayNameUsersMeSetDisplayNamePostQueryParams = zod.object({
  "display_name": zod.string()
})

export const SetDisplayNameUsersMeSetDisplayNamePostResponse = zod.object({
  "message": zod.string()
})

/**
 * Set the team number for the current user

Parameters:
    team_number (int): The team number to set

Returns:
    MessageResponse: A message indicating that the team number was set
 * @summary Set Team Number
 */
export const SetTeamNumberUsersMeSetTeamNumberPostQueryParams = zod.object({
  "team_number": zod.number()
})

export const SetTeamNumberUsersMeSetTeamNumberPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Check if a username and email is unique

Parameters:
    username (str): The username to check
    email (str): The email to check

Returns:
    MessageResponse: A message indicating whether the username is unique
 * @summary Check Unique Username
 */
export const CheckUniqueUsernameAuthCheckUniqueUsernameGetQueryParams = zod.object({
  "username": zod.string(),
  "email": zod.string()
})

export const CheckUniqueUsernameAuthCheckUniqueUsernameGetResponse = zod.unknown()

/**
 * Given an email, create a verification code and send it to the user

If an identity is found, attach the user to the verification code

Parameters:
    email (str): The email to create a verification code for
 * @summary Create Verification Code
 */
export const CreateVerificationCodeAuthCreateVerificationCodePostQueryParams = zod.object({
  "email": zod.string()
})

export const CreateVerificationCodeAuthCreateVerificationCodePostResponse = zod.unknown()

/**
 * Verify a verification code for a user

Given an email and a verification code, verify the verification code

If an identity is found, the verification code must be attached to the user to be validated.
    This would occour when verifying an email from the profile page when their email was not yet verified

The code's created_at should be less than VERIFICATION_CODE_EXPIRE_MINUTES to be validated.

Parameters:
    email (str): The email to verify the verification code for
    code (int): The verification code to verify
 * @summary Verify Verification Code
 */
export const VerifyVerificationCodeAuthVerifyVerificationCodePostQueryParams = zod.object({
  "email": zod.string(),
  "code": zod.string()
})

export const VerifyVerificationCodeAuthVerifyVerificationCodePostResponse = zod.unknown()

