/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import * as zod from 'zod';


/**
 * Get all custom events for a season

Parameters:
    season_uuid (`UUID`): The UUID of the season to get custom events for

Returns:
    list[EventResponse]: A list of all custom events for the season
 * @summary Get Custom Events
 */
export const GetCustomEventsEventCustomSeasonUuidGetParams = zod.object({
  "season_uuid": zod.string()
})

export const GetCustomEventsEventCustomSeasonUuidGetResponseItem = zod.object({
  "uuid": zod.string().uuid(),
  "season": zod.string().uuid(),
  "event_code": zod.string(),
  "name": zod.string(),
  "type": zod.string(),
  "city": zod.string(),
  "country": zod.string(),
  "start_date": zod.string().datetime({}),
  "end_date": zod.string().datetime({}),
  "pits_generated": zod.boolean(),
  "custom": zod.boolean(),
  "created_at": zod.string().datetime({})
})
export const GetCustomEventsEventCustomSeasonUuidGetResponse = zod.array(GetCustomEventsEventCustomSeasonUuidGetResponseItem)

/**
 * Create a custom event for a season

Parameters:
    season_uuid (`UUID`): The UUID of the season to create a custom event for
    data (`CustomEventRequest`): The UUID of the season to create a custom event for

Returns:
    EventResponse: The created custom event
 * @summary Create Custom Event
 */
export const CreateCustomEventEventCustomSeasonUuidCreatePostParams = zod.object({
  "season_uuid": zod.string().uuid()
})

export const CreateCustomEventEventCustomSeasonUuidCreatePostBody = zod.object({
  "season_uuid": zod.string().uuid(),
  "event_code": zod.string(),
  "event_name": zod.string(),
  "event_type": zod.string(),
  "event_city": zod.string(),
  "event_country": zod.string(),
  "event_start_date": zod.string(),
  "event_end_date": zod.string()
})

export const CreateCustomEventEventCustomSeasonUuidCreatePostResponse = zod.object({
  "uuid": zod.string().uuid(),
  "season": zod.string().uuid(),
  "event_code": zod.string(),
  "name": zod.string(),
  "type": zod.string(),
  "city": zod.string(),
  "country": zod.string(),
  "start_date": zod.string().datetime({}),
  "end_date": zod.string().datetime({}),
  "pits_generated": zod.boolean(),
  "custom": zod.boolean(),
  "created_at": zod.string().datetime({})
})

