/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.1
 */
import type {
  BodyUploadImagesUploadImagesPost,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././client';

/**
 * @summary Upload Images
 */
export type uploadImagesUploadImagesPostResponse200 = {
  data: unknown
  status: 200
}

export type uploadImagesUploadImagesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type uploadImagesUploadImagesPostResponseSuccess = (uploadImagesUploadImagesPostResponse200) & {
  headers: Headers;
};
export type uploadImagesUploadImagesPostResponseError = (uploadImagesUploadImagesPostResponse422) & {
  headers: Headers;
};

export type uploadImagesUploadImagesPostResponse = (uploadImagesUploadImagesPostResponseSuccess | uploadImagesUploadImagesPostResponseError)

export const getUploadImagesUploadImagesPostUrl = () => {


  

  return `/upload/images`
}

export const uploadImagesUploadImagesPost = async (bodyUploadImagesUploadImagesPost: BodyUploadImagesUploadImagesPost, options?: RequestInit): Promise<uploadImagesUploadImagesPostResponse> => {
    const formData = new FormData();
bodyUploadImagesUploadImagesPost.files.forEach(value => formData.append(`files`, value));

  return customInstance<uploadImagesUploadImagesPostResponse>(getUploadImagesUploadImagesPostUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}


