/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.1
 */
import type {
  BodyUploadImageUploadImagePost,
  HTTPValidationError,
  UploadImageUploadImagePostParams
} from '../model';

import { customInstance } from '.././client';

/**
 * @summary Upload Image
 */
export type uploadImageUploadImagePostResponse200 = {
  data: unknown
  status: 200
}

export type uploadImageUploadImagePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadImageUploadImagePostResponseSuccess = (uploadImageUploadImagePostResponse200) & {
  headers: Headers;
};
export type uploadImageUploadImagePostResponseError = (uploadImageUploadImagePostResponse422) & {
  headers: Headers;
};

export type uploadImageUploadImagePostResponse = (uploadImageUploadImagePostResponseSuccess | uploadImageUploadImagePostResponseError)

export const getUploadImageUploadImagePostUrl = (params: UploadImageUploadImagePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/upload/image?${stringifiedParams}` : `/upload/image`
}

export const uploadImageUploadImagePost = async (bodyUploadImageUploadImagePost: BodyUploadImageUploadImagePost,
    params: UploadImageUploadImagePostParams, options?: RequestInit): Promise<uploadImageUploadImagePostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadImageUploadImagePost.file);

  return customInstance<uploadImageUploadImagePostResponse>(getUploadImageUploadImagePostUrl(params),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

