services:
  web:
    build: ./scouting
    container_name: open-scouting
    command: gunicorn --workers 3 --chdir scouting scouting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./scouting/.env.production
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./scouting/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/usr/src/app/staticfiles
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: postgres
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./scouting/.env.production
    restart: unless-stopped

volumes:
  db-data:
  staticfiles: