services:
  web:
    build: ./scouting
    container_name: open-scouting
    command: gunicorn --workers 3 --chdir scouting scouting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env.production
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./scouting/nginx.conf:/etc/nginx/nginx.conf 
      - staticfiles:/usr/src/app/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.production

volumes:
  staticfiles: