services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: unless-stopped
      volumes:
          - ./mailpit-data:/data
      ports:
          - 8025:8025
          - 1025:1025
      environment:
          MP_MAX_MESSAGES: 5000
          MP_DATABASE: /data/mailpit.db
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
  mailpit-data: