/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type {
  CreatePasskeyPasskeysRegisterCreatePostParams,
  CreateVerificationPasskeyPasskeysVerificationCreatePostParams,
  HTTPValidationError,
  MessageResponse,
  PasskeyResponse,
  VerifyLoginPasskeyPasskeysLoginVerifyPostBody,
  VerifyLoginPasskeyPasskeysLoginVerifyPostParams,
  VerifyPasskeyPasskeysRegisterVerifyPostBody,
  VerifyPasskeyPasskeysRegisterVerifyPostParams,
  VerifyVerificationPasskeyPasskeysVerificationVerifyPostBody,
  VerifyVerificationPasskeyPasskeysVerificationVerifyPostParams
} from '../model';

import { customInstance } from '.././client';

export type createPasskeyPasskeysRegisterCreatePostResponse200 = {
  data: unknown
  status: 200
}

export type createPasskeyPasskeysRegisterCreatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createPasskeyPasskeysRegisterCreatePostResponseSuccess = (createPasskeyPasskeysRegisterCreatePostResponse200) & {
  headers: Headers;
};
export type createPasskeyPasskeysRegisterCreatePostResponseError = (createPasskeyPasskeysRegisterCreatePostResponse422) & {
  headers: Headers;
};

export type createPasskeyPasskeysRegisterCreatePostResponse = (createPasskeyPasskeysRegisterCreatePostResponseSuccess | createPasskeyPasskeysRegisterCreatePostResponseError)

export const getCreatePasskeyPasskeysRegisterCreatePostUrl = (params?: CreatePasskeyPasskeysRegisterCreatePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/passkeys/register/create?${stringifiedParams}` : `/passkeys/register/create`
}

/**
 * Begin the passkey registration process
 *
 * Requires either verification_code_uuid or passkey_uuid to verify the user's identity, unless the account is less than PASSKEY_NO_VERIFICATION_MINUTES minutes old
 * @summary Create Passkey
 */
export const createPasskeyPasskeysRegisterCreatePost = async (params?: CreatePasskeyPasskeysRegisterCreatePostParams, options?: Parameters<typeof customInstance>[1]): Promise<createPasskeyPasskeysRegisterCreatePostResponse> => {

  return customInstance<createPasskeyPasskeysRegisterCreatePostResponse>(getCreatePasskeyPasskeysRegisterCreatePostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}


export type verifyPasskeyPasskeysRegisterVerifyPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type verifyPasskeyPasskeysRegisterVerifyPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type verifyPasskeyPasskeysRegisterVerifyPostResponseSuccess = (verifyPasskeyPasskeysRegisterVerifyPostResponse200) & {
  headers: Headers;
};
export type verifyPasskeyPasskeysRegisterVerifyPostResponseError = (verifyPasskeyPasskeysRegisterVerifyPostResponse422) & {
  headers: Headers;
};

export type verifyPasskeyPasskeysRegisterVerifyPostResponse = (verifyPasskeyPasskeysRegisterVerifyPostResponseSuccess | verifyPasskeyPasskeysRegisterVerifyPostResponseError)

export const getVerifyPasskeyPasskeysRegisterVerifyPostUrl = (params: VerifyPasskeyPasskeysRegisterVerifyPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/passkeys/register/verify?${stringifiedParams}` : `/passkeys/register/verify`
}

/**
 * Verify the passkey registration
 * @summary Verify Passkey
 */
export const verifyPasskeyPasskeysRegisterVerifyPost = async (verifyPasskeyPasskeysRegisterVerifyPostBody: VerifyPasskeyPasskeysRegisterVerifyPostBody,
    params: VerifyPasskeyPasskeysRegisterVerifyPostParams, options?: Parameters<typeof customInstance>[1]): Promise<verifyPasskeyPasskeysRegisterVerifyPostResponse> => {

  return customInstance<verifyPasskeyPasskeysRegisterVerifyPostResponse>(getVerifyPasskeyPasskeysRegisterVerifyPostUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyPasskeyPasskeysRegisterVerifyPostBody)
  }
);}


export type createLoginPasskeyPasskeysLoginCreatePostResponse200 = {
  data: unknown
  status: 200
}

export type createLoginPasskeyPasskeysLoginCreatePostResponseSuccess = (createLoginPasskeyPasskeysLoginCreatePostResponse200) & {
  headers: Headers;
};
;

export type createLoginPasskeyPasskeysLoginCreatePostResponse = (createLoginPasskeyPasskeysLoginCreatePostResponseSuccess)

export const getCreateLoginPasskeyPasskeysLoginCreatePostUrl = () => {




  return `/passkeys/login/create`
}

/**
 * Begin the passkey login process
 * @summary Create Login Passkey
 */
export const createLoginPasskeyPasskeysLoginCreatePost = async ( options?: Parameters<typeof customInstance>[1]): Promise<createLoginPasskeyPasskeysLoginCreatePostResponse> => {

  return customInstance<createLoginPasskeyPasskeysLoginCreatePostResponse>(getCreateLoginPasskeyPasskeysLoginCreatePostUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


export type verifyLoginPasskeyPasskeysLoginVerifyPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type verifyLoginPasskeyPasskeysLoginVerifyPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type verifyLoginPasskeyPasskeysLoginVerifyPostResponseSuccess = (verifyLoginPasskeyPasskeysLoginVerifyPostResponse200) & {
  headers: Headers;
};
export type verifyLoginPasskeyPasskeysLoginVerifyPostResponseError = (verifyLoginPasskeyPasskeysLoginVerifyPostResponse422) & {
  headers: Headers;
};

export type verifyLoginPasskeyPasskeysLoginVerifyPostResponse = (verifyLoginPasskeyPasskeysLoginVerifyPostResponseSuccess | verifyLoginPasskeyPasskeysLoginVerifyPostResponseError)

export const getVerifyLoginPasskeyPasskeysLoginVerifyPostUrl = (params: VerifyLoginPasskeyPasskeysLoginVerifyPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/passkeys/login/verify?${stringifiedParams}` : `/passkeys/login/verify`
}

/**
 * Verify the passkey login
 * @summary Verify Login Passkey
 */
export const verifyLoginPasskeyPasskeysLoginVerifyPost = async (verifyLoginPasskeyPasskeysLoginVerifyPostBody: VerifyLoginPasskeyPasskeysLoginVerifyPostBody,
    params: VerifyLoginPasskeyPasskeysLoginVerifyPostParams, options?: Parameters<typeof customInstance>[1]): Promise<verifyLoginPasskeyPasskeysLoginVerifyPostResponse> => {

  return customInstance<verifyLoginPasskeyPasskeysLoginVerifyPostResponse>(getVerifyLoginPasskeyPasskeysLoginVerifyPostUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyLoginPasskeyPasskeysLoginVerifyPostBody)
  }
);}


export type createVerificationPasskeyPasskeysVerificationCreatePostResponse200 = {
  data: unknown
  status: 200
}

export type createVerificationPasskeyPasskeysVerificationCreatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createVerificationPasskeyPasskeysVerificationCreatePostResponseSuccess = (createVerificationPasskeyPasskeysVerificationCreatePostResponse200) & {
  headers: Headers;
};
export type createVerificationPasskeyPasskeysVerificationCreatePostResponseError = (createVerificationPasskeyPasskeysVerificationCreatePostResponse422) & {
  headers: Headers;
};

export type createVerificationPasskeyPasskeysVerificationCreatePostResponse = (createVerificationPasskeyPasskeysVerificationCreatePostResponseSuccess | createVerificationPasskeyPasskeysVerificationCreatePostResponseError)

export const getCreateVerificationPasskeyPasskeysVerificationCreatePostUrl = (params: CreateVerificationPasskeyPasskeysVerificationCreatePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/passkeys/verification/create?${stringifiedParams}` : `/passkeys/verification/create`
}

/**
 * Begin the passkey verification process
 * @summary Create Verification Passkey
 */
export const createVerificationPasskeyPasskeysVerificationCreatePost = async (params: CreateVerificationPasskeyPasskeysVerificationCreatePostParams, options?: Parameters<typeof customInstance>[1]): Promise<createVerificationPasskeyPasskeysVerificationCreatePostResponse> => {

  return customInstance<createVerificationPasskeyPasskeysVerificationCreatePostResponse>(getCreateVerificationPasskeyPasskeysVerificationCreatePostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}


export type verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type verifyVerificationPasskeyPasskeysVerificationVerifyPostResponseSuccess = (verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse200) & {
  headers: Headers;
};
export type verifyVerificationPasskeyPasskeysVerificationVerifyPostResponseError = (verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse422) & {
  headers: Headers;
};

export type verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse = (verifyVerificationPasskeyPasskeysVerificationVerifyPostResponseSuccess | verifyVerificationPasskeyPasskeysVerificationVerifyPostResponseError)

export const getVerifyVerificationPasskeyPasskeysVerificationVerifyPostUrl = (params: VerifyVerificationPasskeyPasskeysVerificationVerifyPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/passkeys/verification/verify?${stringifiedParams}` : `/passkeys/verification/verify`
}

/**
 * Verify the passkey verification
 * @summary Verify Verification Passkey
 */
export const verifyVerificationPasskeyPasskeysVerificationVerifyPost = async (verifyVerificationPasskeyPasskeysVerificationVerifyPostBody: VerifyVerificationPasskeyPasskeysVerificationVerifyPostBody,
    params: VerifyVerificationPasskeyPasskeysVerificationVerifyPostParams, options?: Parameters<typeof customInstance>[1]): Promise<verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse> => {

  return customInstance<verifyVerificationPasskeyPasskeysVerificationVerifyPostResponse>(getVerifyVerificationPasskeyPasskeysVerificationVerifyPostUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(verifyVerificationPasskeyPasskeysVerificationVerifyPostBody)
  }
);}


export type getPasskeysPasskeysGetGetResponse200 = {
  data: PasskeyResponse[]
  status: 200
}

export type getPasskeysPasskeysGetGetResponseSuccess = (getPasskeysPasskeysGetGetResponse200) & {
  headers: Headers;
};
;

export type getPasskeysPasskeysGetGetResponse = (getPasskeysPasskeysGetGetResponseSuccess)

export const getGetPasskeysPasskeysGetGetUrl = () => {




  return `/passkeys/get`
}

/**
 * Get the passkeys for the current user
 * @summary Get Passkeys
 */
export const getPasskeysPasskeysGetGet = async ( options?: Parameters<typeof customInstance>[1]): Promise<getPasskeysPasskeysGetGetResponse> => {

  return customInstance<getPasskeysPasskeysGetGetResponse>(getGetPasskeysPasskeysGetGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type deletePasskeyPasskeysDeleteUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type deletePasskeyPasskeysDeleteUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deletePasskeyPasskeysDeleteUuidDeleteResponseSuccess = (deletePasskeyPasskeysDeleteUuidDeleteResponse200) & {
  headers: Headers;
};
export type deletePasskeyPasskeysDeleteUuidDeleteResponseError = (deletePasskeyPasskeysDeleteUuidDeleteResponse422) & {
  headers: Headers;
};

export type deletePasskeyPasskeysDeleteUuidDeleteResponse = (deletePasskeyPasskeysDeleteUuidDeleteResponseSuccess | deletePasskeyPasskeysDeleteUuidDeleteResponseError)

export const getDeletePasskeyPasskeysDeleteUuidDeleteUrl = (uuid: string,) => {




  return `/passkeys/delete/${uuid}`
}

/**
 * Delete a passkey on the server
 *
 * Parameters:
 *     uuid (uuid): The uuid of the passkey to delete
 *
 * Returns:
 *     MessageResponse: A message indicating that the passkey was deleted
 * @summary Delete Passkey
 */
export const deletePasskeyPasskeysDeleteUuidDelete = async (uuid: string, options?: Parameters<typeof customInstance>[1]): Promise<deletePasskeyPasskeysDeleteUuidDeleteResponse> => {

  return customInstance<deletePasskeyPasskeysDeleteUuidDeleteResponse>(getDeletePasskeyPasskeysDeleteUuidDeleteUrl(uuid),
  {
    ...options,
    method: 'DELETE'


  }
);}


