/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */

export interface AdminEventResponse {
  uuid: string;
  season: string;
  event_code: string;
  name: string;
  type: string;
  city: string;
  country: string;
  start_date: string;
  end_date: string;
  pits_generated: boolean;
  custom: boolean;
  created_at: string;
  match_scouting_submissions: number;
  pits: number;
}
