/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface ChangePasswordRequest {
  password: string;
  verification_code_uuid?: string | null;
  passkey_uuid?: string | null;
}
