/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface ChangeEmailRequest {
  email: string;
  verification_code_uuid?: string | null;
  passkey_uuid?: string | null;
}
