/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { CreateReportRequestReportReason } from './createReportRequestReportReason';
import type { CreateReportRequestType } from './createReportRequestType';

export interface CreateReportRequest {
  type: CreateReportRequestType;
  content_uuid: string;
  report_reason: CreateReportRequestReportReason;
  report_details: string;
}
