/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { DataMatchValue } from './dataMatchValue';

export interface DataOtherStatEntry {
  field_uuid: string;
  field_type: string;
  field_name: string;
  values: DataMatchValue[];
}
