/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { DataCapabilityStatEntry } from './dataCapabilityStatEntry';
import type { DataOtherStatEntry } from './dataOtherStatEntry';
import type { DataSummaryEntry } from './dataSummaryEntry';
import type { DataTeamResponseAuton } from './dataTeamResponseAuton';
import type { DataTeamResponseTeleop } from './dataTeamResponseTeleop';

export interface DataTeamResponse {
  team_number: number;
  nickname: string | null;
  teleop: DataTeamResponseTeleop;
  auton: DataTeamResponseAuton;
  capability: DataCapabilityStatEntry[];
  other: DataOtherStatEntry[];
  summary: DataSummaryEntry[];
}
