/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface EditPitFieldRequest {
  season_uuid: string;
  name: string;
  field_type: string;
  options: string;
  order: number;
  organization_uuid: string;
  field_uuid: string;
}
