/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface EventInfoResponse {
  match_scouting_submissions: number;
  match_scouting_answers: number;
  pits: number;
  pit_answers: number;
  pits_complete: number;
  pits_incomplete: number;
  pits_not_started: number;
}
