/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { EventRepairDataType } from './eventRepairDataType';

export interface EventRepair {
  name: string;
  data_uuid: string;
  data_created_at: string;
  data_type: EventRepairDataType;
  repair_type: 'missing_season';
}
