/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface GamePieceRepairRequest {
  data_uuid: string;
  content_uuid?: string | null;
  data_type: 'game_piece';
  repair_type: 'missing_season';
}
