/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type GamePieceRepairDataType = typeof GamePieceRepairDataType[keyof typeof GamePieceRepairDataType];


export const GamePieceRepairDataType = {
  game_piece: 'game_piece',
} as const;
