/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.1
 */

export interface GamepieceResponse {
  uuid: string;
  season: string;
  name: string;
  created_at: string;
}
