/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.1
 */

export type GetDataDataGetGetParams = {
year: number;
event_codes?: string | null;
team_numbers?: string | null;
};
