/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { PitAnswerResponse } from './pitAnswerResponse';

export interface GetPitsResponse {
  uuid: string;
  team_number: number;
  nickname: string;
  created_at: string;
  answers: PitAnswerResponse[];
}
