/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.1
 */
import type { MatchScoutingFieldOptions } from './matchScoutingFieldOptions';

export interface MatchScoutingFieldRequest {
  uuid?: string | null;
  name: string;
  description: string | null;
  season_uuid: string;
  field_type: string;
  stat_type: string;
  required: boolean;
  order: number;
  organization_uuid?: string | null;
  parent_uuid?: string | null;
  options: MatchScoutingFieldOptions;
  choices?: unknown[];
  game_piece_uuid?: string | null;
}
