/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MatchScoutingPresetResponsePreset } from './matchScoutingPresetResponsePreset';

export interface MatchScoutingPresetResponse {
  name: string;
  preset: MatchScoutingPresetResponsePreset;
}
