/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MatchScoutingAnswerRepairRequestRepairType } from './matchScoutingAnswerRepairRequestRepairType';

export interface MatchScoutingAnswerRepairRequest {
  data_uuid: string;
  content_uuid?: string | null;
  data_type: 'match_scouting_answer';
  repair_type: MatchScoutingAnswerRepairRequestRepairType;
}
