/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.2
 */
import type { MatchScoutingFieldOptions } from './matchScoutingFieldOptions';

export interface MatchScoutingFieldResponse {
  uuid?: string | null;
  name: string;
  description: string | null;
  field_type: string;
  stat_type: string;
  game_piece_uuid?: string | null;
  required: boolean;
  options: MatchScoutingFieldOptions;
  choices?: unknown[];
  order: number;
  organization_id?: string | null;
}
