/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type MatchScoutingFieldRepairDataType = typeof MatchScoutingFieldRepairDataType[keyof typeof MatchScoutingFieldRepairDataType];


export const MatchScoutingFieldRepairDataType = {
  match_scouting_field: 'match_scouting_field',
} as const;
