/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type MatchScoutingFieldRepairRequestRepairType = typeof MatchScoutingFieldRepairRequestRepairType[keyof typeof MatchScoutingFieldRepairRequestRepairType];


export const MatchScoutingFieldRepairRequestRepairType = {
  missing_season: 'missing_season',
  missing_game_piece: 'missing_game_piece',
} as const;
