/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface MatchScoutingFieldResponse {
  uuid?: string | null;
  name: string;
  field_type: string;
  stat_type: string;
  game_piece_id?: string | null;
  required: boolean;
  options?: unknown[] | null;
  order: number;
  organization_id?: string | null;
}
