/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type MatchScoutingAnswerRepairRepairType = typeof MatchScoutingAnswerRepairRepairType[keyof typeof MatchScoutingAnswerRepairRepairType];


export const MatchScoutingAnswerRepairRepairType = {
  missing_field: 'missing_field',
  missing_submission: 'missing_submission',
} as const;
