/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { MatchScoutingPresetResponsePreset } from './matchScoutingPresetResponsePreset';

export interface MatchScoutingPresetResponse {
  name: string;
  preset: MatchScoutingPresetResponsePreset;
}
