/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type MatchScoutingSubmissionRepairDataType = typeof MatchScoutingSubmissionRepairDataType[keyof typeof MatchScoutingSubmissionRepairDataType];


export const MatchScoutingSubmissionRepairDataType = {
  match_scouting_submission: 'match_scouting_submission',
} as const;
