/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface MatchScoutingSubmissionRepairRequest {
  data_uuid: string;
  repair_data_uuid: string;
  data_type: 'match_scouting_submission';
  repair_type: 'missing_event';
}
