/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MyDataTypes } from './myDataTypes';

export interface MyDataResponse {
  uuid: string;
  type: MyDataTypes;
  name: string;
  created_at: string;
}
