/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface OrganizationMemberResponse {
  uuid: string;
  organization: string;
  user: string;
  role: string;
  created_at: string;
}
