/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.2
 */

export interface OrganizationResponse {
  uuid: string;
  name: string;
  description: string;
  created_at: string;
}
