/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { PasskeyResponseTransports } from './passkeyResponseTransports';

export interface PasskeyResponse {
  uuid: string;
  transports: PasskeyResponseTransports;
  created_at: string;
}
