/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export interface PitAnswerResponse {
  uuid: string;
  field_uuid: string;
  value: string | boolean | number;
  username: string;
  created_at: string;
}
