/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.2
 */
import type { PitFieldOptions } from './pitFieldOptions';

export interface PitFieldRequest {
  season_uuid: string;
  name: string;
  description: string | null;
  field_type: string;
  options: PitFieldOptions;
  order: number;
  organization_uuid?: string | null;
}
