/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { PitScoutingAnswerRepairDataType } from './pitScoutingAnswerRepairDataType';
import type { PitScoutingAnswerRepairRepairType } from './pitScoutingAnswerRepairRepairType';

export interface PitScoutingAnswerRepair {
  name: string;
  data_uuid: string;
  data_created_at: string;
  data_type: PitScoutingAnswerRepairDataType;
  repair_type: PitScoutingAnswerRepairRepairType;
}
