/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export interface PitScoutingFieldRepairRequest {
  data_uuid: string;
  content_uuid?: string | null;
  data_type: 'pit_scouting_field';
  repair_type: 'missing_season';
}
