/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export interface PitScoutingAnswerReportDetails {
  uuid: string;
  field_uuid: string;
  value: string;
  team_uuid: string;
  team_number: number;
  created_at: string;
}
