/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { PitScoutingAnswerRepairRequestRepairType } from './pitScoutingAnswerRepairRequestRepairType';

export interface PitScoutingAnswerRepairRequest {
  data_uuid: string;
  content_uuid: string | null;
  data_type: 'pit_scouting_answer';
  repair_type: PitScoutingAnswerRepairRequestRepairType;
}
