/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type PitScoutingAnswerRepairDataType = typeof PitScoutingAnswerRepairDataType[keyof typeof PitScoutingAnswerRepairDataType];


export const PitScoutingAnswerRepairDataType = {
  pit_scouting_answer: 'pit_scouting_answer',
} as const;
