/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { RegistrationCredentialResponse } from './registrationCredentialResponse';

export interface RegistrationResponse {
  id: string;
  rawId: string;
  response: RegistrationCredentialResponse;
  type: string;
  clientExtensionResults: unknown;
  authenticatorAttachment: string;
  challenge_uuid: string;
}
