/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.1
 */
import type { ReorderPitField } from './reorderPitField';

export type ReorderPitFieldsRequest = ReorderPitField[];
