/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { ReorderMatchScoutingField } from './reorderMatchScoutingField';

export type ReorderMatchScoutingFieldsRequest = ReorderMatchScoutingField[];
