/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { EventReportDetails } from './eventReportDetails';
import type { MatchScoutingAnswerReportDetails } from './matchScoutingAnswerReportDetails';
import type { MatchScoutingSubmissionReportDetails } from './matchScoutingSubmissionReportDetails';
import type { PitScoutingAnswerReportDetails } from './pitScoutingAnswerReportDetails';
import type { ReportResponseReportReason } from './reportResponseReportReason';
import type { ReportResponseType } from './reportResponseType';
import type { TeamPitReportDetails } from './teamPitReportDetails';

export interface ReportResponse {
  uuid: string;
  type: ReportResponseType;
  content_uuid: string;
  content_details: MatchScoutingSubmissionReportDetails | MatchScoutingAnswerReportDetails | TeamPitReportDetails | PitScoutingAnswerReportDetails | EventReportDetails | null;
  report_reason: ReportResponseReportReason;
  report_details: string;
  created_at: string;
}
