/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type ScoutingFieldRepairRepairType = typeof ScoutingFieldRepairRepairType[keyof typeof ScoutingFieldRepairRepairType];


export const ScoutingFieldRepairRepairType = {
  missing_season: 'missing_season',
  missing_game_piece: 'missing_game_piece',
} as const;
