/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { ScoutingFieldRepairRequestRepairType } from './scoutingFieldRepairRequestRepairType';

export interface ScoutingFieldRepairRequest {
  data_uuid: string;
  content_uuid?: string | null;
  data_type: 'scouting_field';
  repair_type: ScoutingFieldRepairRequestRepairType;
}
