/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SeasonResponse {
  year: number;
  name: string;
  active: boolean;
  uuid: string;
  created_at: string;
}
