/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface SeasonResponse {
  year: number;
  name: string;
  active: boolean;
  uuid: string;
  created_at: string;
}
