/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { SendVerificationCodeEmailVerificationCodePostStyle } from './sendVerificationCodeEmailVerificationCodePostStyle';

export type SendVerificationCodeEmailVerificationCodePostParams = {
email: string;
code: number;
style?: SendVerificationCodeEmailVerificationCodePostStyle;
};
