/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type SendVerificationCodeEmailVerificationCodePostStyle = typeof SendVerificationCodeEmailVerificationCodePostStyle[keyof typeof SendVerificationCodeEmailVerificationCodePostStyle];


export const SendVerificationCodeEmailVerificationCodePostStyle = {
  verification_code: 'verification_code',
  forgot_password: 'forgot_password',
} as const;
