/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface ServerStatsResponse {
  seasons: number;
  events_scouted: number;
  match_scouting_submissions: number;
  pits_scouted: number;
}
