/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SignupRequest {
  username: string;
  email: string;
  password: string;
  confirm_password: string;
  team_number: number;
  display_name: string;
}
