/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.2
 */

export interface SubmissionResponse {
  uuid: string;
  event_name: string;
  event_code: string;
  team_number: number;
  match_number: number;
  match_type: string;
  answers: number;
  created_at: string;
}
