/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type TeamPitRepairDataType = typeof TeamPitRepairDataType[keyof typeof TeamPitRepairDataType];


export const TeamPitRepairDataType = {
  team_pit: 'team_pit',
} as const;
