/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { TeamPitRepairRequestRepairType } from './teamPitRepairRequestRepairType';

export interface TeamPitRepairRequest {
  data_uuid: string;
  repair_data_uuid: string;
  data_type: 'team_pit';
  repair_type: TeamPitRepairRequestRepairType;
}
