/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type TeamPitRepairRepairType = typeof TeamPitRepairRepairType[keyof typeof TeamPitRepairRepairType];


export const TeamPitRepairRepairType = {
  missing_season: 'missing_season',
  missing_event: 'missing_event',
} as const;
