/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type UserSettingType = typeof UserSettingType[keyof typeof UserSettingType];


export const UserSettingType = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  json: 'json',
} as const;
