/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export interface BaseSettings {
  created_at?: unknown | null;
  created_by?: unknown | null;
  favorite_events?: unknown[] | null;
}
