/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type CheckUniqueUsernameAuthCheckUniqueUsernameGetParams = {
username?: string | null;
email?: string | null;
};
