/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type CreateReportRequestType = typeof CreateReportRequestType[keyof typeof CreateReportRequestType];


export const CreateReportRequestType = {
  match_scouting_submission: 'match_scouting_submission',
  match_scouting_answer: 'match_scouting_answer',
  team_pit: 'team_pit',
  pit_scouting_answer: 'pit_scouting_answer',
  event: 'event',
} as const;
