/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type CreateReportRequestReportReason = typeof CreateReportRequestReportReason[keyof typeof CreateReportRequestReportReason];


export const CreateReportRequestReportReason = {
  spam: 'spam',
  innaccurate: 'innaccurate',
  inappropriate: 'inappropriate',
  offensive: 'offensive',
  duplicate: 'duplicate',
  other: 'other',
} as const;
