/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.2
 */

export interface CustomEventRequest {
  season_uuid: string;
  event_code: string;
  event_name: string;
  event_type: string;
  event_city: string;
  event_country: string;
  event_start_date: string;
  event_end_date: string;
}
