/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface CustomEventRequest {
  season_uuid: string;
  event_code: string;
  event_name: string;
  event_type: string;
  event_city: string;
  event_country: string;
  event_start_date: string;
  event_end_date: string;
}
