/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { DataMatchValue } from './dataMatchValue';

export interface DataNumericStatEntry {
  field_uuid: string;
  field_type: string;
  field_name: string;
  values: DataMatchValue[];
  min: number;
  max: number;
  avg: number;
}
