/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { DataFiltersEvent } from './dataFiltersEvent';
import type { DataFiltersTeam } from './dataFiltersTeam';

export interface DataFiltersResponse {
  events: DataFiltersEvent[];
  teams: DataFiltersTeam[];
}
