/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface EventRepairRequest {
  data_uuid: string;
  repair_data_uuid: string;
  data_type: 'event';
  repair_type: 'missing_season';
}
