/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface EventReportDetails {
  uuid: string;
  season_uuid: string;
  event_code: string;
  name: string;
  type: string;
  city: string;
  country: string;
  start_date: string;
  end_date: string;
  custom: boolean;
  created_at: string;
}
