/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface EventRepairRequest {
  data_uuid: string;
  content_uuid?: string | null;
  data_type: 'event';
  repair_type: 'missing_season';
}
