/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { FieldChoiceResponse } from './fieldChoiceResponse';

export interface FieldOptionsResponse {
  uuid: string;
  choices: FieldChoiceResponse[] | null;
  default: number | null;
  minimum: number | null;
  maximum: number | null;
  created_at: string;
}
