/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type FieldType = typeof FieldType[keyof typeof FieldType];


export const FieldType = {
  section: 'section',
  string: 'string',
  large_number: 'large_number',
  small_number: 'small_number',
  coarse_small_number: 'coarse_small_number',
  boolean: 'boolean',
  choice: 'choice',
  multiple_choice: 'multiple_choice',
  number: 'number',
  image: 'image',
} as const;
