/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export interface ForgotPasswordRequest {
  email: string;
  password: string;
  verification_code_uuid: string;
}
