/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.2
 */

export type GetDataDataGetGetParams = {
year: number;
event_codes?: string | null;
team_numbers?: string | null;
};
