/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */

export interface MatchScoutingFieldOptions {
  choices: unknown[];
  default: number;
  minimum: number;
  maximum: number;
}
