/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MatchScoutingFieldRepairRequestRepairType } from './matchScoutingFieldRepairRequestRepairType';

export interface MatchScoutingFieldRepairRequest {
  data_uuid: string;
  repair_data_uuid: string;
  data_type: 'match_scouting_field';
  repair_type: MatchScoutingFieldRepairRequestRepairType;
}
