/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MatchScoutingFieldRepairDataType } from './matchScoutingFieldRepairDataType';
import type { MatchScoutingFieldRepairRepairType } from './matchScoutingFieldRepairRepairType';

export interface MatchScoutingFieldRepair {
  name: string;
  data_uuid: string;
  data_created_at: string;
  data_type: MatchScoutingFieldRepairDataType;
  repair_type: MatchScoutingFieldRepairRepairType;
}
