/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MatchScoutingAnswerReportDetails } from './matchScoutingAnswerReportDetails';

export interface MatchScoutingSubmissionReportDetails {
  uuid: string;
  event_uuid: string;
  season_uuid: string;
  team_number: number;
  match_number: number;
  match_type: string;
  answers_count: number;
  answers: MatchScoutingAnswerReportDetails[];
}
