/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { MatchScoutingFieldOptions } from './matchScoutingFieldOptions';

export interface MatchScoutingSeasonFieldsResponse {
  uuid: string;
  name: string;
  description: string | null;
  field_type: string;
  stat_type: string;
  game_piece_uuid?: string | null;
  required: boolean;
  options: MatchScoutingFieldOptions;
  order: number;
  organization_id: string | null;
  fields?: MatchScoutingSeasonFieldsResponse[];
}
