/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface MatchScoutingResponse {
  uuid: string;
  user: string | null;
  event: string;
  team_number: number;
  match_number: number;
  match_type: string;
  created_at: string;
}
