/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { FieldOptionsResponse } from './fieldOptionsResponse';
import type { FieldType } from './fieldType';
import type { StatType } from './statType';

export interface MatchScoutingFieldResponse {
  uuid: string;
  season_uuid: string | null;
  organization_uuid: string | null;
  parent_uuid: string | null;
  name: string;
  description: string | null;
  scouting_type: 'match';
  field_type: FieldType;
  stat_type: StatType | null;
  game_piece_uuid: string | null;
  required: boolean;
  options: FieldOptionsResponse | null;
  order: number;
  archived: boolean;
  created_at: string;
}
