/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type MatchScoutingAnswerRepairDataType = typeof MatchScoutingAnswerRepairDataType[keyof typeof MatchScoutingAnswerRepairDataType];


export const MatchScoutingAnswerRepairDataType = {
  match_scouting_answer: 'match_scouting_answer',
} as const;
