/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface MatchScoutingAnswerReportDetails {
  uuid: string;
  field_uuid: string;
  value: string;
  created_at?: string | null;
}
