/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import type { MatchScoutingFieldOptions } from './matchScoutingFieldOptions';

export interface MatchScoutingFieldResponse {
  uuid?: string | null;
  name: string;
  field_type: string;
  stat_type: string;
  game_piece_uuid?: string | null;
  required: boolean;
  options: MatchScoutingFieldOptions;
  choices?: unknown[];
  order: number;
  organization_id?: string | null;
}
