/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.2
 */

export interface MatchScoutingResponse {
  uuid: string;
  user: string | null;
  event: string;
  team_number: number;
  match_number: number;
  match_type: string;
  created_at: string;
}
