/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { MatchScoutingFieldRepairRequestRepairType } from './matchScoutingFieldRepairRequestRepairType';

export interface MatchScoutingFieldRepairRequest {
  data_uuid: string;
  content_uuid?: string | null;
  data_type: 'match_scouting_field';
  repair_type: MatchScoutingFieldRepairRequestRepairType;
}
