/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface MatchScoutingFieldRepairResponse {
  uuid: string;
  name: string;
  season_year: number | null;
  game_piece_name: string | null;
  archived: boolean;
  created_at: string;
}
