/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface MatchScoutingFieldRequest {
  name: string;
  season_uuid: string;
  field_type: string;
  stat_type: string;
  required: boolean;
  order: number;
  organization_uuid?: string | null;
  parent_uuid?: string | null;
  options?: unknown[] | null;
  game_piece_uuid?: string | null;
}
