/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { MatchScoutingSubmissionRepairDataType } from './matchScoutingSubmissionRepairDataType';

export interface MatchScoutingSubmissionRepair {
  name: string;
  data_uuid: string;
  data_created_at: string;
  data_type: MatchScoutingSubmissionRepairDataType;
  repair_type: 'missing_event';
}
