/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export interface OrganizationMemberResponse {
  uuid: string;
  organization: string;
  user: string;
  role: string;
  created_at: string;
}
