/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export interface OrganizationResponse {
  uuid: string;
  name: string;
  description: string;
  created_at: string;
}
