/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.1
 */

export interface OrganizationMemberResponse {
  uuid: string;
  organization: string;
  user: string;
  role: string;
  created_at: string;
}
