/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.2
 */
import type { PitFieldOptions } from './pitFieldOptions';

export interface PitFieldResponse {
  uuid: string;
  season: string;
  name: string;
  description: string | null;
  required: boolean;
  field_type: string;
  options: PitFieldOptions;
  order: number;
  organization: string | null;
  created_at: string;
}
