/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import type { PitFieldOptions } from './pitFieldOptions';

export interface PitFieldRequest {
  season_uuid: string;
  name: string;
  field_type: string;
  options: PitFieldOptions;
  order: number;
  organization_uuid?: string | null;
}
