/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { PitFieldOptions } from './pitFieldOptions';

export interface PitFieldRequest {
  uuid?: string | null;
  season_uuid: string;
  name: string;
  description: string | null;
  required: boolean;
  field_type: string;
  options: PitFieldOptions;
  order: number;
  organization_uuid?: string | null;
}
