/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type PitScoutingFieldRepairDataType = typeof PitScoutingFieldRepairDataType[keyof typeof PitScoutingFieldRepairDataType];


export const PitScoutingFieldRepairDataType = {
  pit_scouting_field: 'pit_scouting_field',
} as const;
