/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */

export type PitScoutingAnswerRepairRequestRepairType = typeof PitScoutingAnswerRepairRequestRepairType[keyof typeof PitScoutingAnswerRepairRequestRepairType];


export const PitScoutingAnswerRepairRequestRepairType = {
  missing_field: 'missing_field',
  missing_team: 'missing_team',
} as const;
