/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { FieldOptionsResponse } from './fieldOptionsResponse';
import type { FieldType } from './fieldType';

export interface PitScoutingFieldResponse {
  uuid: string;
  season_uuid: string | null;
  organization_uuid: string | null;
  name: string;
  description: string | null;
  scouting_type: 'pit';
  field_type: FieldType;
  required: boolean;
  options: FieldOptionsResponse | null;
  order: number;
  archived: boolean;
  created_at: string;
}
