/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.1
 */
import type { ReorderMatchScoutingField } from './reorderMatchScoutingField';

export type ReorderMatchScoutingFieldsRequest = ReorderMatchScoutingField[];
