/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type ReportResponseReportReason = typeof ReportResponseReportReason[keyof typeof ReportResponseReportReason];


export const ReportResponseReportReason = {
  spam: 'spam',
  innaccurate: 'innaccurate',
  inappropriate: 'inappropriate',
  offensive: 'offensive',
  duplicate: 'duplicate',
  other: 'other',
} as const;
