/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type ScoutingType = typeof ScoutingType[keyof typeof ScoutingType];


export const ScoutingType = {
  match: 'match',
  pit: 'pit',
} as const;
