/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type ScoutingFieldRepairRequestRepairType = typeof ScoutingFieldRepairRequestRepairType[keyof typeof ScoutingFieldRepairRequestRepairType];


export const ScoutingFieldRepairRequestRepairType = {
  missing_season: 'missing_season',
  missing_game_piece: 'missing_game_piece',
} as const;
