/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { TeamPitRepairDataType } from './teamPitRepairDataType';
import type { TeamPitRepairRepairType } from './teamPitRepairRepairType';

export interface TeamPitRepair {
  name: string;
  data_uuid: string;
  data_created_at: string;
  data_type: TeamPitRepairDataType;
  repair_type: TeamPitRepairRepairType;
}
