/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { UserSettingType } from './userSettingType';

export interface UserSetting {
  key: string;
  value: unknown | null;
  name: string;
  description: string;
  type: UserSettingType;
}
