/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type { UserSettingType } from './userSettingType';

export interface UserSetting {
  key: string;
  value: unknown | null;
  name: string;
  description: string | null;
  section: string | null;
  visible: boolean;
  type: UserSettingType;
}
