/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type { UserResponse } from './userResponse';

export interface UserMeResponse {
  authenticated: boolean;
  user: UserResponse | null;
}
