/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.1
 */
import type { ValidationErrorCtx } from './validationErrorCtx';

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}
