/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */

export type VerifyVerificationPasskeyPasskeysVerificationVerifyPostParams = {
challenge_uuid: string;
email: string;
};
