/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import type {
  HTTPValidationError,
  MessageResponse,
  SeasonCreate,
  SeasonResponse
} from '.././model';

import { customInstance } from '.././client';

/**
 * Get all seasons on the server

Returns:
    list[Season]: A list of all seasons
 * @summary Get Seasons
 */
export type getSeasonsSeasonsGetResponse200 = {
  data: SeasonResponse[]
  status: 200
}
    
export type getSeasonsSeasonsGetResponseSuccess = (getSeasonsSeasonsGetResponse200) & {
  headers: Headers;
};
;

export type getSeasonsSeasonsGetResponse = (getSeasonsSeasonsGetResponseSuccess)

export const getGetSeasonsSeasonsGetUrl = () => {


  

  return `/seasons`
}

export const getSeasonsSeasonsGet = async ( options?: RequestInit): Promise<getSeasonsSeasonsGetResponse> => {
  
  return customInstance<getSeasonsSeasonsGetResponse>(getGetSeasonsSeasonsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Get the active season on the server

Returns:
    Season: The active season
 * @summary Get Active Season
 */
export type getActiveSeasonSeasonsActiveGetResponse200 = {
  data: SeasonResponse | null
  status: 200
}
    
export type getActiveSeasonSeasonsActiveGetResponseSuccess = (getActiveSeasonSeasonsActiveGetResponse200) & {
  headers: Headers;
};
;

export type getActiveSeasonSeasonsActiveGetResponse = (getActiveSeasonSeasonsActiveGetResponseSuccess)

export const getGetActiveSeasonSeasonsActiveGetUrl = () => {


  

  return `/seasons/active`
}

export const getActiveSeasonSeasonsActiveGet = async ( options?: RequestInit): Promise<getActiveSeasonSeasonsActiveGetResponse> => {
  
  return customInstance<getActiveSeasonSeasonsActiveGetResponse>(getGetActiveSeasonSeasonsActiveGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a new season

Requires superuser access

Parameters:
    data (`SeasonCreate`): The data to create the season

Returns:
    `SeasonResponse`: The created season
 * @summary Create Season
 */
export type createSeasonSeasonsCreatePostResponse200 = {
  data: SeasonResponse
  status: 200
}

export type createSeasonSeasonsCreatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createSeasonSeasonsCreatePostResponseSuccess = (createSeasonSeasonsCreatePostResponse200) & {
  headers: Headers;
};
export type createSeasonSeasonsCreatePostResponseError = (createSeasonSeasonsCreatePostResponse422) & {
  headers: Headers;
};

export type createSeasonSeasonsCreatePostResponse = (createSeasonSeasonsCreatePostResponseSuccess | createSeasonSeasonsCreatePostResponseError)

export const getCreateSeasonSeasonsCreatePostUrl = () => {


  

  return `/seasons/create`
}

export const createSeasonSeasonsCreatePost = async (seasonCreate: SeasonCreate, options?: RequestInit): Promise<createSeasonSeasonsCreatePostResponse> => {
  
  return customInstance<createSeasonSeasonsCreatePostResponse>(getCreateSeasonSeasonsCreatePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      seasonCreate,)
  }
);}


/**
 * Delete a season

Requires superuser access

Parameters:
    season_uuid (`UUID`): The UUID of the season to delete

Returns:
    `MessageResponse`: A message indicating that the season was deleted
 * @summary Delete Season
 */
export type deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteSeasonSeasonsDeleteSeasonUuidDeleteResponseSuccess = (deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse200) & {
  headers: Headers;
};
export type deleteSeasonSeasonsDeleteSeasonUuidDeleteResponseError = (deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse422) & {
  headers: Headers;
};

export type deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse = (deleteSeasonSeasonsDeleteSeasonUuidDeleteResponseSuccess | deleteSeasonSeasonsDeleteSeasonUuidDeleteResponseError)

export const getDeleteSeasonSeasonsDeleteSeasonUuidDeleteUrl = (seasonUuid: string,) => {


  

  return `/seasons/delete/${seasonUuid}`
}

export const deleteSeasonSeasonsDeleteSeasonUuidDelete = async (seasonUuid: string, options?: RequestInit): Promise<deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse> => {
  
  return customInstance<deleteSeasonSeasonsDeleteSeasonUuidDeleteResponse>(getDeleteSeasonSeasonsDeleteSeasonUuidDeleteUrl(seasonUuid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


