/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MessageResponse,
  SeasonResponse
} from '.././model';


export const getGetSeasonsSeasonsGetResponseMock = (): SeasonResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({year: faker.number.int({min: undefined, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), uuid: faker.string.uuid(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getGetActiveSeasonSeasonsActiveGetResponseMock = (): SeasonResponse | null => (faker.helpers.arrayElement([{year: faker.number.int({min: undefined, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), uuid: faker.string.uuid(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'},null,]))

export const getCreateSeasonSeasonsCreatePostResponseMock = (overrideResponse: Partial< SeasonResponse > = {}): SeasonResponse => ({year: faker.number.int({min: undefined, max: undefined}), name: faker.string.alpha({length: {min: 10, max: 20}}), active: faker.datatype.boolean(), uuid: faker.string.uuid(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getDeleteSeasonSeasonsDeleteSeasonUuidDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetSeasonsSeasonsGetMockHandler = (overrideResponse?: SeasonResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SeasonResponse[]> | SeasonResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/seasons', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetSeasonsSeasonsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetActiveSeasonSeasonsActiveGetMockHandler = (overrideResponse?: SeasonResponse | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SeasonResponse | null> | SeasonResponse | null), options?: RequestHandlerOptions) => {
  return http.get('*/seasons/active', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetActiveSeasonSeasonsActiveGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateSeasonSeasonsCreatePostMockHandler = (overrideResponse?: SeasonResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SeasonResponse> | SeasonResponse), options?: RequestHandlerOptions) => {
  return http.post('*/seasons/create', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateSeasonSeasonsCreatePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteSeasonSeasonsDeleteSeasonUuidDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/seasons/delete/:seasonUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteSeasonSeasonsDeleteSeasonUuidDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getSeasonsMock = () => [
  getGetSeasonsSeasonsGetMockHandler(),
  getGetActiveSeasonSeasonsActiveGetMockHandler(),
  getCreateSeasonSeasonsCreatePostMockHandler(),
  getDeleteSeasonSeasonsDeleteSeasonUuidDeleteMockHandler()
]
