/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import * as zod from 'zod';


/**
 * Get all notifications for the current user

Requires user authentication

Returns:
    list[Notification]: A list of all notifications
 * @summary Get Notifications
 */
export const GetNotificationsNotificationsGetResponseItem = zod.object({
  "uuid": zod.string().uuid(),
  "title": zod.string(),
  "message": zod.string(),
  "type": zod.string(),
  "action_type": zod.union([zod.string(),zod.null()]),
  "action_data": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]),
  "read": zod.boolean(),
  "created_at": zod.string().datetime({"offset":true})
})
export const GetNotificationsNotificationsGetResponse = zod.array(GetNotificationsNotificationsGetResponseItem)

/**
 * Delete a notification

Requires user authentication

Parameters:
    notification_uuid (`UUID`): The UUID of the notification to delete

Returns:
    MessageResponse: A message indicating that the notification was deleted
 * @summary Delete Notification
 */
export const DeleteNotificationNotificationsDeleteNotificationUuidDeleteParams = zod.object({
  "notification_uuid": zod.string().uuid()
})

export const DeleteNotificationNotificationsDeleteNotificationUuidDeleteResponse = zod.object({
  "message": zod.string()
})

/**
 * Mark a notification as read or unread

Requires user authentication

Parameters:
    notification_uuid (`UUID`): The UUID of the notification to mark as read
    read (`bool`): The read status of the notification

Returns:
    MessageResponse: A message indicating that the notification was marked as read or unread
 * @summary Set Notification Read
 */
export const SetNotificationReadNotificationsSetReadNotificationUuidReadPutParams = zod.object({
  "notification_uuid": zod.string().uuid(),
  "read": zod.boolean()
})

export const SetNotificationReadNotificationsSetReadNotificationUuidReadPutResponse = zod.object({
  "message": zod.string()
})

/**
 * Add a notification to the database

This is used when the client creates a notification that needs to be synced to the server

Requires user authentication

Parameters:
    data (`NotificationRequest`): The data to create the notification with

Returns:
    NotificationResponse: The notification that was created
 * @summary Add Notification
 */
export const AddNotificationNotificationsSendPostBody = zod.object({
  "uuid": zod.string().uuid(),
  "title": zod.string(),
  "message": zod.string(),
  "type": zod.string(),
  "action_type": zod.union([zod.string(),zod.null()]),
  "action_data": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]),
  "read": zod.boolean(),
  "deleted": zod.boolean()
})

export const AddNotificationNotificationsSendPostResponse = zod.union([zod.object({
  "uuid": zod.string().uuid(),
  "title": zod.string(),
  "message": zod.string(),
  "type": zod.string(),
  "action_type": zod.union([zod.string(),zod.null()]),
  "action_data": zod.union([zod.record(zod.string(), zod.unknown()),zod.null()]),
  "read": zod.boolean(),
  "created_at": zod.string().datetime({"offset":true})
}),zod.object({
  "message": zod.string()
})])

