/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MessageResponse,
  PitFieldResponse
} from '.././model';


export const getGetPitFieldsPitsFieldsSeasonUuidGetResponseMock = (): PitFieldResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), season: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), field_type: faker.string.alpha({length: {min: 10, max: 20}}), options: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), order: faker.number.int({min: undefined, max: undefined}), organization: faker.helpers.arrayElement([faker.string.uuid(),null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getClearPitFieldsPitsFieldsSeasonUuidClearDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getCreatePitFieldPitsFieldsSeasonUuidCreatePostResponseMock = (overrideResponse: Partial< PitFieldResponse > = {}): PitFieldResponse => ({uuid: faker.string.uuid(), season: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), field_type: faker.string.alpha({length: {min: 10, max: 20}}), options: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), order: faker.number.int({min: undefined, max: undefined}), organization: faker.helpers.arrayElement([faker.string.uuid(),null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getEditPitFieldPitsFieldsSeasonUuidEditFieldUuidPatchResponseMock = (overrideResponse: Partial< PitFieldResponse > = {}): PitFieldResponse => ({uuid: faker.string.uuid(), season: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), field_type: faker.string.alpha({length: {min: 10, max: 20}}), options: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), order: faker.number.int({min: undefined, max: undefined}), organization: faker.helpers.arrayElement([faker.string.uuid(),null,]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getDeletePitFieldPitsFieldsFieldUuidDeleteDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getSubmitPitPitsSubmitSeasonUuidTeamNumberPostResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetPitFieldsPitsFieldsSeasonUuidGetMockHandler = (overrideResponse?: PitFieldResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PitFieldResponse[]> | PitFieldResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/pits/fields/:seasonUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPitFieldsPitsFieldsSeasonUuidGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClearPitFieldsPitsFieldsSeasonUuidClearDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/pits/fields/:seasonUuid/clear', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClearPitFieldsPitsFieldsSeasonUuidClearDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreatePitFieldPitsFieldsSeasonUuidCreatePostMockHandler = (overrideResponse?: PitFieldResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PitFieldResponse> | PitFieldResponse), options?: RequestHandlerOptions) => {
  return http.post('*/pits/fields/:seasonUuid/create', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePitFieldPitsFieldsSeasonUuidCreatePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getEditPitFieldPitsFieldsSeasonUuidEditFieldUuidPatchMockHandler = (overrideResponse?: PitFieldResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<PitFieldResponse> | PitFieldResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/pits/fields/:seasonUuid/edit/:fieldUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getEditPitFieldPitsFieldsSeasonUuidEditFieldUuidPatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeletePitFieldPitsFieldsFieldUuidDeleteDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/pits/fields/:fieldUuid/delete', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeletePitFieldPitsFieldsFieldUuidDeleteDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetPitsPitsGetSeasonUuidPostMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.post('*/pits/get/:seasonUuid', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getSubmitPitPitsSubmitSeasonUuidTeamNumberPostMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.post('*/pits/submit/:seasonUuid/:teamNumber', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSubmitPitPitsSubmitSeasonUuidTeamNumberPostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getPitScoutingMock = () => [
  getGetPitFieldsPitsFieldsSeasonUuidGetMockHandler(),
  getClearPitFieldsPitsFieldsSeasonUuidClearDeleteMockHandler(),
  getCreatePitFieldPitsFieldsSeasonUuidCreatePostMockHandler(),
  getEditPitFieldPitsFieldsSeasonUuidEditFieldUuidPatchMockHandler(),
  getDeletePitFieldPitsFieldsFieldUuidDeleteDeleteMockHandler(),
  getGetPitsPitsGetSeasonUuidPostMockHandler(),
  getSubmitPitPitsSubmitSeasonUuidTeamNumberPostMockHandler()
]
