# Generated by Django 5.1.2 on 2025-09-09 11:56

from django.db import migrations


def remove_bad_page_views(apps, schema_editor):
    PageView = apps.get_model("analytics", "PageView")
    urls = [
        "/",
        "/contribute",
        "/pits",
        "/advanced_data",
        "/authentication/",
        "/authentication",
        "/authentication/profile",
    ]
    PageView.objects.exclude(url__in=urls).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remove_bad_page_views, migrations.RunPython.noop),
    ]
