/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MatchScoutingFieldRequest,
  MatchScoutingFieldResponse,
  MessageResponse
} from '.././model';


export const getClearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getCreateSeasonFieldFieldsSeasonSeasonUuidCreatePostResponseMock = (overrideResponse: Partial< MatchScoutingFieldResponse > = {}): MatchScoutingFieldResponse => ({uuid: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(),null,]), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), field_type: faker.string.alpha({length: {min: 10, max: 20}}), stat_type: faker.string.alpha({length: {min: 10, max: 20}}), game_piece_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(),null,]), undefined]), required: faker.datatype.boolean(), options: faker.helpers.arrayElement([faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),null,]), undefined]), order: faker.number.int({min: undefined, max: undefined}), organization_id: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(),null,]), undefined]), ...overrideResponse})

export const getEditSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponseMock = (overrideResponse: Partial< MatchScoutingFieldRequest > = {}): MatchScoutingFieldRequest => ({name: faker.string.alpha({length: {min: 10, max: 20}}), season_uuid: faker.string.uuid(), field_type: faker.string.alpha({length: {min: 10, max: 20}}), stat_type: faker.string.alpha({length: {min: 10, max: 20}}), required: faker.datatype.boolean(), order: faker.number.int({min: undefined, max: undefined}), organization_uuid: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(),null,]), undefined]), parent_uuid: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(),null,]), undefined]), options: faker.helpers.arrayElement([faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})),null,]), undefined]), game_piece_uuid: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(),null,]), undefined]), ...overrideResponse})

export const getDeleteFieldFieldsDeleteFieldUuidDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetSeasonFieldsFieldsSeasonSeasonUuidGetMockHandler = (overrideResponse?: unknown[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown[]> | unknown[]), options?: RequestHandlerOptions) => {
  return http.get('*/fields/season/:seasonUuid', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getClearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/fields/season/:seasonUuid/clear', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateSeasonFieldFieldsSeasonSeasonUuidCreatePostMockHandler = (overrideResponse?: MatchScoutingFieldResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MatchScoutingFieldResponse> | MatchScoutingFieldResponse), options?: RequestHandlerOptions) => {
  return http.post('*/fields/season/:seasonUuid/create', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateSeasonFieldFieldsSeasonSeasonUuidCreatePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getEditSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostMockHandler = (overrideResponse?: MatchScoutingFieldRequest | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MatchScoutingFieldRequest> | MatchScoutingFieldRequest), options?: RequestHandlerOptions) => {
  return http.post('*/fields/season/:seasonUuid/edit/:fieldUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getEditSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetMatchScoutingFieldPresetsFieldsGetPresetsGetMockHandler = (overrideResponse?: unknown[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown[]> | unknown[]), options?: RequestHandlerOptions) => {
  return http.get('*/fields/get_presets', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getDeleteFieldFieldsDeleteFieldUuidDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/fields/delete/:fieldUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteFieldFieldsDeleteFieldUuidDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getMatchScoutingFieldsMock = () => [
  getGetSeasonFieldsFieldsSeasonSeasonUuidGetMockHandler(),
  getClearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteMockHandler(),
  getCreateSeasonFieldFieldsSeasonSeasonUuidCreatePostMockHandler(),
  getEditSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostMockHandler(),
  getGetMatchScoutingFieldPresetsFieldsGetPresetsGetMockHandler(),
  getDeleteFieldFieldsDeleteFieldUuidDeleteMockHandler()
]
