/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  HTTPValidationError,
  MatchScoutingFieldRequest,
  MatchScoutingFieldResponse,
  MessageResponse
} from '.././model';

import { customInstance } from '.././client';

/**
 * Get all match scouting fields for a season

Parameters:
    season_uuid (`UUID`): The UUID of the season to get fields for

Returns:
    `list[MatchScoutingField]`: A list of all match scouting fields for the season
 * @summary Get Season Fields
 */
export type getSeasonFieldsFieldsSeasonSeasonUuidGetResponse200 = {
  data: unknown[]
  status: 200
}

export type getSeasonFieldsFieldsSeasonSeasonUuidGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getSeasonFieldsFieldsSeasonSeasonUuidGetResponseSuccess = (getSeasonFieldsFieldsSeasonSeasonUuidGetResponse200) & {
  headers: Headers;
};
export type getSeasonFieldsFieldsSeasonSeasonUuidGetResponseError = (getSeasonFieldsFieldsSeasonSeasonUuidGetResponse422) & {
  headers: Headers;
};

export type getSeasonFieldsFieldsSeasonSeasonUuidGetResponse = (getSeasonFieldsFieldsSeasonSeasonUuidGetResponseSuccess | getSeasonFieldsFieldsSeasonSeasonUuidGetResponseError)

export const getGetSeasonFieldsFieldsSeasonSeasonUuidGetUrl = (seasonUuid: string,) => {


  

  return `/fields/season/${seasonUuid}`
}

export const getSeasonFieldsFieldsSeasonSeasonUuidGet = async (seasonUuid: string, options?: RequestInit): Promise<getSeasonFieldsFieldsSeasonSeasonUuidGetResponse> => {
  
  return customInstance<getSeasonFieldsFieldsSeasonSeasonUuidGetResponse>(getGetSeasonFieldsFieldsSeasonSeasonUuidGetUrl(seasonUuid),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Clear all match scouting fields for a season

Requires superuser access

Parameters:
    season_uuid (`UUID`): The UUID of the season to clear fields for

Returns:
    `MessageResponse`: A message indicating that the fields were cleared
 * @summary Clear Season Fields
 */
export type clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponseSuccess = (clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse200) & {
  headers: Headers;
};
export type clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponseError = (clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse422) & {
  headers: Headers;
};

export type clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse = (clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponseSuccess | clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponseError)

export const getClearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteUrl = (seasonUuid: string,) => {


  

  return `/fields/season/${seasonUuid}/clear`
}

export const clearSeasonFieldsFieldsSeasonSeasonUuidClearDelete = async (seasonUuid: string, options?: RequestInit): Promise<clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse> => {
  
  return customInstance<clearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteResponse>(getClearSeasonFieldsFieldsSeasonSeasonUuidClearDeleteUrl(seasonUuid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Create a new match scouting field

Requires superuser access

Parameters:
    season_uuid (`UUID`): The UUID of the season to create the field for
    data (MatchScoutingFieldRequest): The data to create the field

Returns:
    `MatchScoutingField`: The created field
 * @summary Create Season Field
 */
export type createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse200 = {
  data: MatchScoutingFieldResponse
  status: 200
}

export type createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponseSuccess = (createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse200) & {
  headers: Headers;
};
export type createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponseError = (createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse422) & {
  headers: Headers;
};

export type createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse = (createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponseSuccess | createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponseError)

export const getCreateSeasonFieldFieldsSeasonSeasonUuidCreatePostUrl = (seasonUuid: string,) => {


  

  return `/fields/season/${seasonUuid}/create`
}

export const createSeasonFieldFieldsSeasonSeasonUuidCreatePost = async (seasonUuid: string,
    matchScoutingFieldRequest: MatchScoutingFieldRequest, options?: RequestInit): Promise<createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse> => {
  
  return customInstance<createSeasonFieldFieldsSeasonSeasonUuidCreatePostResponse>(getCreateSeasonFieldFieldsSeasonSeasonUuidCreatePostUrl(seasonUuid),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      matchScoutingFieldRequest,)
  }
);}


/**
 * Edit a match scouting field

Requires superuser access

Parameters:
    season_uuid (`UUID`): The UUID of the season to edit the field for
    field_uuid (`UUID`): The UUID of the field to edit
    data (MatchScoutingFieldRequest): The data to edit the field

Returns:
    `MatchScoutingField`: The edited field
 * @summary Edit Season Field
 */
export type editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse200 = {
  data: MatchScoutingFieldResponse
  status: 200
}

export type editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponseSuccess = (editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse200) & {
  headers: Headers;
};
export type editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponseError = (editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse422) & {
  headers: Headers;
};

export type editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse = (editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponseSuccess | editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponseError)

export const getEditSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostUrl = (seasonUuid: string,
    fieldUuid: string,) => {


  

  return `/fields/season/${seasonUuid}/edit/${fieldUuid}`
}

export const editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPost = async (seasonUuid: string,
    fieldUuid: string,
    matchScoutingFieldRequest: MatchScoutingFieldRequest, options?: RequestInit): Promise<editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse> => {
  
  return customInstance<editSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostResponse>(getEditSeasonFieldFieldsSeasonSeasonUuidEditFieldUuidPostUrl(seasonUuid,fieldUuid),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      matchScoutingFieldRequest,)
  }
);}


/**
 * Get all JSON match scouting field presets

Requires superuser access

Returns:
    `list[Any]`: A list of all match scouting field presets
 * @summary Get Match Scouting Field Presets
 */
export type getMatchScoutingFieldPresetsFieldsGetPresetsGetResponse200 = {
  data: unknown[]
  status: 200
}
    
export type getMatchScoutingFieldPresetsFieldsGetPresetsGetResponseSuccess = (getMatchScoutingFieldPresetsFieldsGetPresetsGetResponse200) & {
  headers: Headers;
};
;

export type getMatchScoutingFieldPresetsFieldsGetPresetsGetResponse = (getMatchScoutingFieldPresetsFieldsGetPresetsGetResponseSuccess)

export const getGetMatchScoutingFieldPresetsFieldsGetPresetsGetUrl = () => {


  

  return `/fields/get_presets`
}

export const getMatchScoutingFieldPresetsFieldsGetPresetsGet = async ( options?: RequestInit): Promise<getMatchScoutingFieldPresetsFieldsGetPresetsGetResponse> => {
  
  return customInstance<getMatchScoutingFieldPresetsFieldsGetPresetsGetResponse>(getGetMatchScoutingFieldPresetsFieldsGetPresetsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Delete a match scouting field

Requires superuser access

Parameters:
    field_uuid (`UUID`): The UUID of the field to delete

Returns:
    `MessageResponse`: A message indicating that the field was deleted
 * @summary Delete Field
 */
export type deleteFieldFieldsDeleteFieldUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteFieldFieldsDeleteFieldUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteFieldFieldsDeleteFieldUuidDeleteResponseSuccess = (deleteFieldFieldsDeleteFieldUuidDeleteResponse200) & {
  headers: Headers;
};
export type deleteFieldFieldsDeleteFieldUuidDeleteResponseError = (deleteFieldFieldsDeleteFieldUuidDeleteResponse422) & {
  headers: Headers;
};

export type deleteFieldFieldsDeleteFieldUuidDeleteResponse = (deleteFieldFieldsDeleteFieldUuidDeleteResponseSuccess | deleteFieldFieldsDeleteFieldUuidDeleteResponseError)

export const getDeleteFieldFieldsDeleteFieldUuidDeleteUrl = (fieldUuid: string,) => {


  

  return `/fields/delete/${fieldUuid}`
}

export const deleteFieldFieldsDeleteFieldUuidDelete = async (fieldUuid: string, options?: RequestInit): Promise<deleteFieldFieldsDeleteFieldUuidDeleteResponse> => {
  
  return customInstance<deleteFieldFieldsDeleteFieldUuidDeleteResponse>(getDeleteFieldFieldsDeleteFieldUuidDeleteUrl(fieldUuid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


