/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import * as zod from 'zod';


/**
 * Submit a match scouting form

Will create a MatchScoutingSubmission for each submission, and then create a MatchScoutingAnswer for each field answer

Parameters:
    data (MatchScoutingRequest): The data to submit the match scouting form

Returns:
    `MatchScoutingSubmission`: The submitted match scouting form
 * @summary Submit Match Scouting
 */
export const SubmitMatchScoutingScoutingSubmitPostBody = zod.object({
  "submission_uuid": zod.string().uuid(),
  "fields": zod.record(zod.string(), zod.unknown()),
  "user_uuid": zod.union([zod.string().uuid(),zod.string()]),
  "year": zod.number(),
  "team_number": zod.number(),
  "match_number": zod.number(),
  "match_type": zod.string(),
  "event_code": zod.string(),
  "event_name": zod.string(),
  "event_type": zod.string(),
  "event_city": zod.string(),
  "event_country": zod.string(),
  "event_start_date": zod.string(),
  "event_end_date": zod.string()
})

export const SubmitMatchScoutingScoutingSubmitPostResponse = zod.object({
  "uuid": zod.string().uuid(),
  "user": zod.union([zod.string().uuid(),zod.null()]),
  "event": zod.string().uuid(),
  "team_number": zod.number(),
  "match_number": zod.number(),
  "match_type": zod.string(),
  "created_at": zod.string().datetime({})
})

