/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import * as zod from 'zod';


/**
 * Return data that the user has submitted
 *
 * This includes MatchScoutingSubmission, MatchScoutingAnswer, TeamPit, PitScoutingAnswer end Event models created by the user
 *
 * First, get every MatchScoutingSubmission, MatchScoutingAnswer, TeamPit, PitScoutingAnswer and
 *     Event model that has a created_by session that is owned by the user
 *
 * Returns:
 *     list[MyDataResponse]: A list of data that the user has submitted
 * @summary Get My Data
 */
export const GetMyDataProfileMyDataGetResponseItem = zod.object({
  "uuid": zod.uuid(),
  "type": zod.enum(['match_scouting_submission', 'match_scouting_answer', 'team_pit', 'pit_scouting_answer', 'event']),
  "name": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})
export const GetMyDataProfileMyDataGetResponse = zod.array(GetMyDataProfileMyDataGetResponseItem)

/**
 * Given type and uuid, delete the data that the user has submitted
 *
 * Ensure that the user has created the data before deleting it
 *
 * Parameters:
 *     type (MyDataTypes): The type of data to delete
 *     uuid (UUID): The uuid of the data to delete
 *
 * Returns:
 *     MessageResponse: A message indicating that the data was deleted
 * @summary Delete My Data
 */
export const DeleteMyDataProfileDeleteTypeUuidDeleteParams = zod.object({
  "type": zod.enum(['match_scouting_submission', 'match_scouting_answer', 'team_pit', 'pit_scouting_answer', 'event']),
  "uuid": zod.uuid()
})

export const DeleteMyDataProfileDeleteTypeUuidDeleteResponse = zod.object({
  "message": zod.string()
})

