/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  EventResponse
} from '.././model';


export const getGetCustomEventsEventCustomSeasonUuidGetResponseMock = (): EventResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), season: faker.string.uuid(), event_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), city: faker.string.alpha({length: {min: 10, max: 20}}), country: faker.string.alpha({length: {min: 10, max: 20}}), start_date: faker.date.past().toISOString().slice(0, 19) + 'Z', end_date: faker.date.past().toISOString().slice(0, 19) + 'Z', pits_generated: faker.datatype.boolean(), custom: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getCreateCustomEventEventCustomSeasonUuidCreatePostResponseMock = (overrideResponse: Partial< EventResponse > = {}): EventResponse => ({uuid: faker.string.uuid(), season: faker.string.uuid(), event_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), city: faker.string.alpha({length: {min: 10, max: 20}}), country: faker.string.alpha({length: {min: 10, max: 20}}), start_date: faker.date.past().toISOString().slice(0, 19) + 'Z', end_date: faker.date.past().toISOString().slice(0, 19) + 'Z', pits_generated: faker.datatype.boolean(), custom: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getGetCustomEventsEventCustomSeasonUuidGetMockHandler = (overrideResponse?: EventResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EventResponse[]> | EventResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/event/custom/:seasonUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCustomEventsEventCustomSeasonUuidGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateCustomEventEventCustomSeasonUuidCreatePostMockHandler = (overrideResponse?: EventResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<EventResponse> | EventResponse), options?: RequestHandlerOptions) => {
  return http.post('*/event/custom/:seasonUuid/create', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCustomEventEventCustomSeasonUuidCreatePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getEventsMock = () => [
  getGetCustomEventsEventCustomSeasonUuidGetMockHandler(),
  getCreateCustomEventEventCustomSeasonUuidCreatePostMockHandler()
]
