/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  CustomEventRequest,
  EventResponse,
  HTTPValidationError
} from '.././model';

import { customInstance } from '.././client';

/**
 * Get all custom events for a season

Parameters:
    season_uuid (`UUID`): The UUID of the season to get custom events for

Returns:
    list[EventResponse]: A list of all custom events for the season
 * @summary Get Custom Events
 */
export type getCustomEventsEventCustomSeasonUuidGetResponse200 = {
  data: EventResponse[]
  status: 200
}

export type getCustomEventsEventCustomSeasonUuidGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getCustomEventsEventCustomSeasonUuidGetResponseSuccess = (getCustomEventsEventCustomSeasonUuidGetResponse200) & {
  headers: Headers;
};
export type getCustomEventsEventCustomSeasonUuidGetResponseError = (getCustomEventsEventCustomSeasonUuidGetResponse422) & {
  headers: Headers;
};

export type getCustomEventsEventCustomSeasonUuidGetResponse = (getCustomEventsEventCustomSeasonUuidGetResponseSuccess | getCustomEventsEventCustomSeasonUuidGetResponseError)

export const getGetCustomEventsEventCustomSeasonUuidGetUrl = (seasonUuid: string,) => {


  

  return `/event/custom/${seasonUuid}`
}

export const getCustomEventsEventCustomSeasonUuidGet = async (seasonUuid: string, options?: RequestInit): Promise<getCustomEventsEventCustomSeasonUuidGetResponse> => {
  
  return customInstance<getCustomEventsEventCustomSeasonUuidGetResponse>(getGetCustomEventsEventCustomSeasonUuidGetUrl(seasonUuid),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Create a custom event for a season

Parameters:
    season_uuid (`UUID`): The UUID of the season to create a custom event for
    data (`CustomEventRequest`): The UUID of the season to create a custom event for

Returns:
    EventResponse: The created custom event
 * @summary Create Custom Event
 */
export type createCustomEventEventCustomSeasonUuidCreatePostResponse200 = {
  data: EventResponse
  status: 200
}

export type createCustomEventEventCustomSeasonUuidCreatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createCustomEventEventCustomSeasonUuidCreatePostResponseSuccess = (createCustomEventEventCustomSeasonUuidCreatePostResponse200) & {
  headers: Headers;
};
export type createCustomEventEventCustomSeasonUuidCreatePostResponseError = (createCustomEventEventCustomSeasonUuidCreatePostResponse422) & {
  headers: Headers;
};

export type createCustomEventEventCustomSeasonUuidCreatePostResponse = (createCustomEventEventCustomSeasonUuidCreatePostResponseSuccess | createCustomEventEventCustomSeasonUuidCreatePostResponseError)

export const getCreateCustomEventEventCustomSeasonUuidCreatePostUrl = (seasonUuid: string,) => {


  

  return `/event/custom/${seasonUuid}/create`
}

export const createCustomEventEventCustomSeasonUuidCreatePost = async (seasonUuid: string,
    customEventRequest: CustomEventRequest, options?: RequestInit): Promise<createCustomEventEventCustomSeasonUuidCreatePostResponse> => {
  
  return customInstance<createCustomEventEventCustomSeasonUuidCreatePostResponse>(getCreateCustomEventEventCustomSeasonUuidCreatePostUrl(seasonUuid),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      customEventRequest,)
  }
);}


