/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import * as zod from 'zod';


/**
 * Get all pits for a season and event
 *
 * Parameters:
 *     season_uuid (`UUID`): The UUID of the season to get pits for
 *     data (`GetPitsForSeasonRequest`): The UUID of the season to get pits for
 *
 * Returns:
 *     list: A list of all pits for the season
 * @summary Get Pits
 */
export const GetPitsPitsGetSeasonUuidEventCodePostParams = zod.object({
  "season_uuid": zod.uuid(),
  "event_code": zod.string()
})

export const GetPitsPitsGetSeasonUuidEventCodePostResponseItem = zod.object({
  "uuid": zod.uuid(),
  "team_number": zod.int(),
  "nickname": zod.string(),
  "created_at": zod.iso.datetime({"offset":true}),
  "answers": zod.array(zod.object({
  "uuid": zod.uuid(),
  "field_uuid": zod.uuid(),
  "value": zod.union([zod.string(),zod.boolean(),zod.int(),zod.number()]),
  "username": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
}))
})
export const GetPitsPitsGetSeasonUuidEventCodePostResponse = zod.array(GetPitsPitsGetSeasonUuidEventCodePostResponseItem)

/**
 * Get the season and event from the uuids. Then, check if a pit with that team number exists.
 * If it does, update that pit
 *
 * For the answers in that pit, find each answer that does not already exist on the server, and add them
 *
 * If a pit does not exist, that means it was created by the client of a user. It should be created.
 *
 * Parameters:
 *     season_uuid (`UUID`): The UUID of the season to get pits for
 *     team_number (`int`): The team number to get pits for
 *     data (`SubmitPitFieldAnswerRequest`): The UUID of the season and event to get pits for
 *
 * Returns:
 *     MessageResponse: A message indicating that the pits were submitted
 * @summary Submit Pit
 */
export const SubmitPitPitsSubmitSeasonUuidTeamNumberPostParams = zod.object({
  "season_uuid": zod.uuid(),
  "team_number": zod.int()
})

export const SubmitPitPitsSubmitSeasonUuidTeamNumberPostBody = zod.object({
  "uuid": zod.uuid(),
  "season_uuid": zod.uuid(),
  "team_number": zod.int(),
  "event_code": zod.string(),
  "answers": zod.array(zod.unknown()),
  "nickname": zod.union([zod.string(),zod.null()])
})

export const SubmitPitPitsSubmitSeasonUuidTeamNumberPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Get all pits
 *
 * Requires superuser access
 *
 * Returns:
 *     list[AdminPitResponse]: A list of all pits
 * @summary Get All Pits
 */
export const GetAllPitsPitsGetGetResponseItem = zod.object({
  "uuid": zod.uuid(),
  "event_name": zod.string(),
  "event_code": zod.string(),
  "team_number": zod.int(),
  "answers": zod.int(),
  "created_at": zod.iso.datetime({"offset":true})
})
export const GetAllPitsPitsGetGetResponse = zod.array(GetAllPitsPitsGetGetResponseItem)

/**
 * Delete a pit
 *
 * Requires superuser access
 *
 * Parameters:
 *     pit_uuid (`UUID`): The UUID of the pit to delete
 *
 * Returns:
 *     MessageResponse: A message indicating that the pit was deleted
 * @summary Delete Pit
 */
export const DeletePitPitsDeletePitUuidDeleteParams = zod.object({
  "pit_uuid": zod.uuid()
})

export const DeletePitPitsDeletePitUuidDeleteResponse = zod.object({
  "message": zod.string()
})

