/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import * as zod from 'zod';


/**
 * @summary Get Server Status
 */
export const GetServerStatusStatusGetResponse = zod.object({
  "version": zod.union([zod.string(),zod.null()]),
  "active_season": zod.string().uuid()
})

/**
 * Get basic server stats, which are displayed on the index page
 * @summary Get Server Stats
 */
export const GetServerStatsStatusStatsGetResponse = zod.object({
  "seasons": zod.number(),
  "events_scouted": zod.number(),
  "match_scouting_submissions": zod.number(),
  "pits_scouted": zod.number()
})

