/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import * as zod from 'zod';


/**
 * @summary Get Server Status
 */
export const GetServerStatusStatusGetResponse = zod.object({
  "version": zod.union([zod.string(),zod.null()]),
  "active_season": zod.string().uuid()
})

