/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  HTTPValidationError,
  MatchScoutingRequest,
  MatchScoutingResponse
} from '.././model';


/**
 * Submit a match scouting form

Will create a MatchScoutingSubmission for each submission, and then create a MatchScoutingAnswer for each field answer

Parameters:
    data (MatchScoutingRequest): The data to submit the match scouting form

Returns:
    `MatchScoutingSubmission`: The submitted match scouting form
 * @summary Submit Match Scouting
 */
export type submitMatchScoutingScoutingSubmitPostResponse200 = {
  data: MatchScoutingResponse
  status: 200
}

export type submitMatchScoutingScoutingSubmitPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type submitMatchScoutingScoutingSubmitPostResponseSuccess = (submitMatchScoutingScoutingSubmitPostResponse200) & {
  headers: Headers;
};
export type submitMatchScoutingScoutingSubmitPostResponseError = (submitMatchScoutingScoutingSubmitPostResponse422) & {
  headers: Headers;
};

export type submitMatchScoutingScoutingSubmitPostResponse = (submitMatchScoutingScoutingSubmitPostResponseSuccess | submitMatchScoutingScoutingSubmitPostResponseError)

export const getSubmitMatchScoutingScoutingSubmitPostUrl = () => {


  

  return `/scouting/submit`
}

export const submitMatchScoutingScoutingSubmitPost = async (matchScoutingRequest: MatchScoutingRequest, options?: RequestInit): Promise<submitMatchScoutingScoutingSubmitPostResponse> => {
  
  const res = await fetch(getSubmitMatchScoutingScoutingSubmitPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      matchScoutingRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: submitMatchScoutingScoutingSubmitPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as submitMatchScoutingScoutingSubmitPostResponse
}


