/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import type {
  HTTPValidationError,
  MatchScoutingRequest,
  MatchScoutingResponse
} from '.././model';

import { customInstance } from '.././client';

/**
 * Submit a match scouting form

Will create a MatchScoutingSubmission for each submission, and then create a MatchScoutingAnswer for each field answer

Parameters:
    data (MatchScoutingRequest): The data to submit the match scouting form

Returns:
    `MatchScoutingSubmission`: The submitted match scouting form
 * @summary Submit Match Scouting
 */
export type submitMatchScoutingScoutingSubmitPostResponse200 = {
  data: MatchScoutingResponse
  status: 200
}

export type submitMatchScoutingScoutingSubmitPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type submitMatchScoutingScoutingSubmitPostResponseSuccess = (submitMatchScoutingScoutingSubmitPostResponse200) & {
  headers: Headers;
};
export type submitMatchScoutingScoutingSubmitPostResponseError = (submitMatchScoutingScoutingSubmitPostResponse422) & {
  headers: Headers;
};

export type submitMatchScoutingScoutingSubmitPostResponse = (submitMatchScoutingScoutingSubmitPostResponseSuccess | submitMatchScoutingScoutingSubmitPostResponseError)

export const getSubmitMatchScoutingScoutingSubmitPostUrl = () => {


  

  return `/scouting/submit`
}

export const submitMatchScoutingScoutingSubmitPost = async (matchScoutingRequest: MatchScoutingRequest, options?: RequestInit): Promise<submitMatchScoutingScoutingSubmitPostResponse> => {
  
  return customInstance<submitMatchScoutingScoutingSubmitPostResponse>(getSubmitMatchScoutingScoutingSubmitPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      matchScoutingRequest,)
  }
);}


