/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GamepieceResponse,
  MessageResponse
} from '.././model';


export const getGetGamepiecesGamepiecesGetResponseMock = (): GamepieceResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), season: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getCreateGamepieceGamepiecesCreatePostResponseMock = (overrideResponse: Partial< GamepieceResponse > = {}): GamepieceResponse => ({uuid: faker.string.uuid(), season: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetSeasonGamepiecesGamepiecesSeasonSeasonUuidGetResponseMock = (): GamepieceResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), season: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getDeleteGamepieceGamepiecesDeleteGamepieceUuidDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetGamepiecesGamepiecesGetMockHandler = (overrideResponse?: GamepieceResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GamepieceResponse[]> | GamepieceResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/gamepieces', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGamepiecesGamepiecesGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateGamepieceGamepiecesCreatePostMockHandler = (overrideResponse?: GamepieceResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GamepieceResponse> | GamepieceResponse), options?: RequestHandlerOptions) => {
  return http.post('*/gamepieces/create', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateGamepieceGamepiecesCreatePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetSeasonGamepiecesGamepiecesSeasonSeasonUuidGetMockHandler = (overrideResponse?: GamepieceResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GamepieceResponse[]> | GamepieceResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/gamepieces/season/:seasonUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetSeasonGamepiecesGamepiecesSeasonSeasonUuidGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteGamepieceGamepiecesDeleteGamepieceUuidDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/gamepieces/delete/:gamepieceUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteGamepieceGamepiecesDeleteGamepieceUuidDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getGamepiecesMock = () => [
  getGetGamepiecesGamepiecesGetMockHandler(),
  getCreateGamepieceGamepiecesCreatePostMockHandler(),
  getGetSeasonGamepiecesGamepiecesSeasonSeasonUuidGetMockHandler(),
  getDeleteGamepieceGamepiecesDeleteGamepieceUuidDeleteMockHandler()
]
