/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type {
  ServerStatsResponse,
  ServerStatusResponse
} from '../model';

import { customInstance } from '.././client';

export type getServerStatusStatusGetResponse200 = {
  data: ServerStatusResponse
  status: 200
}

export type getServerStatusStatusGetResponseSuccess = (getServerStatusStatusGetResponse200) & {
  headers: Headers;
};
;

export type getServerStatusStatusGetResponse = (getServerStatusStatusGetResponseSuccess)

export const getGetServerStatusStatusGetUrl = () => {




  return `/status`
}

/**
 * @summary Get Server Status
 */
export const getServerStatusStatusGet = async ( options?: RequestInit): Promise<getServerStatusStatusGetResponse> => {

  return customInstance<getServerStatusStatusGetResponse>(getGetServerStatusStatusGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type getServerStatsStatusStatsGetResponse200 = {
  data: ServerStatsResponse
  status: 200
}

export type getServerStatsStatusStatsGetResponseSuccess = (getServerStatsStatusStatsGetResponse200) & {
  headers: Headers;
};
;

export type getServerStatsStatusStatsGetResponse = (getServerStatsStatusStatsGetResponseSuccess)

export const getGetServerStatsStatusStatsGetUrl = () => {




  return `/status/stats`
}

/**
 * Get basic server stats, which are displayed on the index page
 * @summary Get Server Stats
 */
export const getServerStatsStatusStatsGet = async ( options?: RequestInit): Promise<getServerStatsStatusStatsGetResponse> => {

  return customInstance<getServerStatsStatusStatsGetResponse>(getGetServerStatsStatusStatsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


