/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type {
  ServerStatusResponse
} from '../model';

import { customInstance } from '.././client';

export type getServerStatusStatusGetResponse200 = {
  data: ServerStatusResponse
  status: 200
}

export type getServerStatusStatusGetResponseSuccess = (getServerStatusStatusGetResponse200) & {
  headers: Headers;
};
;

export type getServerStatusStatusGetResponse = (getServerStatusStatusGetResponseSuccess)

export const getGetServerStatusStatusGetUrl = () => {




  return `/status`
}

/**
 * @summary Get Server Status
 */
export const getServerStatusStatusGet = async ( options?: RequestInit): Promise<getServerStatusStatusGetResponse> => {

  return customInstance<getServerStatusStatusGetResponse>(getGetServerStatusStatusGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


