/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.2
 */
import type {
  ServerStatusResponse
} from '../model';

import { customInstance } from '.././client';

/**
 * @summary Get Server Status
 */
export type getServerStatusStatusGetResponse200 = {
  data: ServerStatusResponse
  status: 200
}

export type getServerStatusStatusGetResponseSuccess = (getServerStatusStatusGetResponse200) & {
  headers: Headers;
};
;

export type getServerStatusStatusGetResponse = (getServerStatusStatusGetResponseSuccess)

export const getGetServerStatusStatusGetUrl = () => {


  

  return `/status`
}

export const getServerStatusStatusGet = async ( options?: RequestInit): Promise<getServerStatusStatusGetResponse> => {
  
  return customInstance<getServerStatusStatusGetResponse>(getGetServerStatusStatusGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

