/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import * as zod from 'zod';


/**
 * @summary Upload Image
 */
export const UploadImageUploadImagePostQueryParams = zod.object({
  "file_uuid": zod.string()
})

export const UploadImageUploadImagePostBody = zod.object({
  "file": zod.instanceof(File)
})

export const UploadImageUploadImagePostResponse = zod.unknown()

/**
 * Given the uploaded file, store it on the server
 *
 * Use the generated URL to assign the image to the user's profile
 *
 * Return the relevant image information
 * @summary Upload Profile Picture
 */
export const UploadProfilePictureUploadProfilePictureMePostBody = zod.object({
  "file": zod.instanceof(File)
})

export const UploadProfilePictureUploadProfilePictureMePostResponse = zod.unknown()

