/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.1.0-beta.1
 */
import * as zod from 'zod';


/**
 * @summary Upload Images
 */
export const UploadImagesUploadImagesPostBody = zod.object({
  "files": zod.array(zod.instanceof(File))
})

export const UploadImagesUploadImagesPostResponse = zod.unknown()

