/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import * as zod from 'zod';


/**
 * @summary Upload Image
 */
export const UploadImageUploadImagePostQueryParams = zod.object({
  "file_uuid": zod.string()
})

export const UploadImageUploadImagePostBody = zod.object({
  "file": zod.instanceof(File)
})

export const UploadImageUploadImagePostResponse = zod.unknown()

