/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import type {
  HTTPValidationError,
  MatchScoutingFieldRequest,
  MatchScoutingFieldResponse,
  MessageResponse,
  PitScoutingFieldRequest,
  PitScoutingFieldResponse,
  ScoutingFieldPresetResponse,
  ScoutingType
} from '../model';

import { customInstance } from '.././client';

export type getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse200 = {
  data: (MatchScoutingFieldResponse | PitScoutingFieldResponse)[]
  status: 200
}

export type getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponseSuccess = (getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse200) & {
  headers: Headers;
};
export type getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponseError = (getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse422) & {
  headers: Headers;
};

export type getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse = (getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponseSuccess | getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponseError)

export const getGetSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetUrl = (seasonUuid: string,
    scoutingType: ScoutingType,) => {




  return `/fields/season/${seasonUuid}/${scoutingType}`
}

/**
 * Get all scouting fields for a season. Takes season uuid and the field type.
 *
 * Parameters:
 *     season_uuid (`UUID`): The UUID of the season to get fields for
 *     scouting_type (`ScoutingType`): The scouting type to get fields for
 *
 * Returns:
 *     list[MatchScoutingFieldResponse | PitScoutingFieldResponse]: A list of all scouting fields for the season
 * @summary Get Season Fields
 */
export const getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGet = async (seasonUuid: string,
    scoutingType: ScoutingType, options?: Parameters<typeof customInstance>[1]): Promise<getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse> => {

  return customInstance<getSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetResponse>(getGetSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeGetUrl(seasonUuid,scoutingType),
  {
    ...options,
    method: 'GET'


  }
);}


export type archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponseSuccess = (archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse200) & {
  headers: Headers;
};
export type archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponseError = (archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse422) & {
  headers: Headers;
};

export type archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse = (archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponseSuccess | archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponseError)

export const getArchiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteUrl = (seasonUuid: string,
    scoutingType: ScoutingType,) => {




  return `/fields/season/${seasonUuid}/${scoutingType}/archive`
}

/**
 * Archive all scouting fields for a season
 *
 * Requires superuser access
 *
 * Parameters:
 *     season_uuid (`UUID`): The UUID of the season to archive fields for
 *     scouting_type (`ScoutingType`): The scouting type to archive fields for
 *
 * Returns:
 *     `MessageResponse`: A message indicating that the fields were archived
 * @summary Archive Season Fields
 */
export const archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDelete = async (seasonUuid: string,
    scoutingType: ScoutingType, options?: Parameters<typeof customInstance>[1]): Promise<archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse> => {

  return customInstance<archiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteResponse>(getArchiveSeasonFieldsFieldsSeasonSeasonUuidScoutingTypeArchiveDeleteUrl(seasonUuid,scoutingType),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type createFieldFieldsCreatePostResponse200 = {
  data: MatchScoutingFieldResponse | PitScoutingFieldResponse
  status: 200
}

export type createFieldFieldsCreatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createFieldFieldsCreatePostResponseSuccess = (createFieldFieldsCreatePostResponse200) & {
  headers: Headers;
};
export type createFieldFieldsCreatePostResponseError = (createFieldFieldsCreatePostResponse422) & {
  headers: Headers;
};

export type createFieldFieldsCreatePostResponse = (createFieldFieldsCreatePostResponseSuccess | createFieldFieldsCreatePostResponseError)

export const getCreateFieldFieldsCreatePostUrl = () => {




  return `/fields/create`
}

/**
 * Create a new scouting field
 *
 * Parameters:
 *     data (`MatchScoutingFieldRequest | PitScoutingFieldRequest`): The data to create the field with
 *
 * Returns:
 *     `MatchScoutingFieldResponse | PitScoutingFieldResponse`: The created field
 *
 * TODO: Allow non-superusers to create organization fields
 * @summary Create Field
 */
export const createFieldFieldsCreatePost = async (matchScoutingFieldRequestPitScoutingFieldRequest: MatchScoutingFieldRequest | PitScoutingFieldRequest, options?: Parameters<typeof customInstance>[1]): Promise<createFieldFieldsCreatePostResponse> => {

  return customInstance<createFieldFieldsCreatePostResponse>(getCreateFieldFieldsCreatePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchScoutingFieldRequestPitScoutingFieldRequest)
  }
);}


export type editFieldFieldsEditPatchResponse200 = {
  data: MatchScoutingFieldResponse | PitScoutingFieldResponse
  status: 200
}

export type editFieldFieldsEditPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type editFieldFieldsEditPatchResponseSuccess = (editFieldFieldsEditPatchResponse200) & {
  headers: Headers;
};
export type editFieldFieldsEditPatchResponseError = (editFieldFieldsEditPatchResponse422) & {
  headers: Headers;
};

export type editFieldFieldsEditPatchResponse = (editFieldFieldsEditPatchResponseSuccess | editFieldFieldsEditPatchResponseError)

export const getEditFieldFieldsEditPatchUrl = () => {




  return `/fields/edit`
}

/**
 * Edit a scouting field
 *
 * Parameters:
 *     data (`MatchScoutingFieldRequest | PitScoutingFieldRequest`): The data to edit the field
 *
 * Returns:
 *     `MatchScoutingFieldResponse | PitScoutingFieldResponse`: The edited field
 * @summary Edit Field
 */
export const editFieldFieldsEditPatch = async (matchScoutingFieldRequestPitScoutingFieldRequest: MatchScoutingFieldRequest | PitScoutingFieldRequest, options?: Parameters<typeof customInstance>[1]): Promise<editFieldFieldsEditPatchResponse> => {

  return customInstance<editFieldFieldsEditPatchResponse>(getEditFieldFieldsEditPatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchScoutingFieldRequestPitScoutingFieldRequest)
  }
);}


export type getFieldPresetsFieldsPresetsScoutingTypeGetResponse200 = {
  data: ScoutingFieldPresetResponse[]
  status: 200
}

export type getFieldPresetsFieldsPresetsScoutingTypeGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getFieldPresetsFieldsPresetsScoutingTypeGetResponseSuccess = (getFieldPresetsFieldsPresetsScoutingTypeGetResponse200) & {
  headers: Headers;
};
export type getFieldPresetsFieldsPresetsScoutingTypeGetResponseError = (getFieldPresetsFieldsPresetsScoutingTypeGetResponse422) & {
  headers: Headers;
};

export type getFieldPresetsFieldsPresetsScoutingTypeGetResponse = (getFieldPresetsFieldsPresetsScoutingTypeGetResponseSuccess | getFieldPresetsFieldsPresetsScoutingTypeGetResponseError)

export const getGetFieldPresetsFieldsPresetsScoutingTypeGetUrl = (scoutingType: ScoutingType,) => {




  return `/fields/presets/${scoutingType}`
}

/**
 * Get all scouting field presets
 *
 * Parameters:
 *     scouting_type (`ScoutingType`): The scouting type to get presets for
 *
 * Returns:
 *     `list[ScoutingFieldPresetResponse]`: A list of all scouting field presets
 * @summary Get Field Presets
 */
export const getFieldPresetsFieldsPresetsScoutingTypeGet = async (scoutingType: ScoutingType, options?: Parameters<typeof customInstance>[1]): Promise<getFieldPresetsFieldsPresetsScoutingTypeGetResponse> => {

  return customInstance<getFieldPresetsFieldsPresetsScoutingTypeGetResponse>(getGetFieldPresetsFieldsPresetsScoutingTypeGetUrl(scoutingType),
  {
    ...options,
    method: 'GET'


  }
);}


export type archiveFieldFieldsArchiveFieldUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type archiveFieldFieldsArchiveFieldUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type archiveFieldFieldsArchiveFieldUuidDeleteResponseSuccess = (archiveFieldFieldsArchiveFieldUuidDeleteResponse200) & {
  headers: Headers;
};
export type archiveFieldFieldsArchiveFieldUuidDeleteResponseError = (archiveFieldFieldsArchiveFieldUuidDeleteResponse422) & {
  headers: Headers;
};

export type archiveFieldFieldsArchiveFieldUuidDeleteResponse = (archiveFieldFieldsArchiveFieldUuidDeleteResponseSuccess | archiveFieldFieldsArchiveFieldUuidDeleteResponseError)

export const getArchiveFieldFieldsArchiveFieldUuidDeleteUrl = (fieldUuid: string,) => {




  return `/fields/archive/${fieldUuid}`
}

/**
 * Archive a scouting field
 *
 * Requires superuser access
 *
 * Parameters:
 *     field_uuid (`UUID`): The UUID of the field to archive
 *
 * Returns:
 *     `MessageResponse`: A message indicating that the field was archived
 *
 * TODO: Allow non-superusers to archive organization fields that belong to their organization
 * @summary Archive Field
 */
export const archiveFieldFieldsArchiveFieldUuidDelete = async (fieldUuid: string, options?: Parameters<typeof customInstance>[1]): Promise<archiveFieldFieldsArchiveFieldUuidDeleteResponse> => {

  return customInstance<archiveFieldFieldsArchiveFieldUuidDeleteResponse>(getArchiveFieldFieldsArchiveFieldUuidDeleteUrl(fieldUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type reorderFieldsFieldsReorderPatchResponse200 = {
  data: (MatchScoutingFieldResponse | PitScoutingFieldResponse)[]
  status: 200
}

export type reorderFieldsFieldsReorderPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type reorderFieldsFieldsReorderPatchResponseSuccess = (reorderFieldsFieldsReorderPatchResponse200) & {
  headers: Headers;
};
export type reorderFieldsFieldsReorderPatchResponseError = (reorderFieldsFieldsReorderPatchResponse422) & {
  headers: Headers;
};

export type reorderFieldsFieldsReorderPatchResponse = (reorderFieldsFieldsReorderPatchResponseSuccess | reorderFieldsFieldsReorderPatchResponseError)

export const getReorderFieldsFieldsReorderPatchUrl = () => {




  return `/fields/reorder`
}

/**
 * Reorder scouting fields
 *
 * Based on the order of the fields in the request, the fields will be reordered to that order.
 * It is assumed that all fields in this request are meant to be reordered together. Only pass fields to this request that you want to reorder.
 * If fields have parents, the parents must be in the request as well. Order children on a different "level" than their parents, but in the order they appear in the list.
 *
 * Parameters:
 *     data (`list[MatchScoutingFieldRequest] | list[PitScoutingFieldRequest]`): The data to reorder the fields
 *
 * Returns:
 *     `list[MatchScoutingFieldResponse | PitScoutingFieldResponse]`: A list of all fields in the new order
 *
 * TODO: Allow non-superusers to reorder organization fields that belong to their organization
 * @summary Reorder Fields
 */
export const reorderFieldsFieldsReorderPatch = async (matchScoutingFieldRequestPitScoutingFieldRequest: MatchScoutingFieldRequest[] | PitScoutingFieldRequest[], options?: Parameters<typeof customInstance>[1]): Promise<reorderFieldsFieldsReorderPatchResponse> => {

  return customInstance<reorderFieldsFieldsReorderPatchResponse>(getReorderFieldsFieldsReorderPatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchScoutingFieldRequestPitScoutingFieldRequest)
  }
);}


