# Generated by Django 5.1.2 on 2025-06-21 18:31

from django.db import migrations


def add_settings_to_users(apps, schema_editor):
    Setting = apps.get_model("authentication", "Settings")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        if not Setting.objects.filter(user=user).exists():
            Setting.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_settings"),
    ]

    operations = [
        migrations.RunPython(add_settings_to_users),
    ]
