# Generated by Django 5.1.2 on 2025-06-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favorite_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
