# Generated by Django 5.1.2 on 2025-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_settings_favorite_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favorite_events',
            field=models.JSONField(blank=True, default=list, help_text="The user's favorite evemts, pinned to the top of their event list", verbose_name='Favorite Events'),
        ),
    ]
