# Generated by Django 5.1.2 on 2025-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_settings_favorite_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='test_bool',
            field=models.BooleanField(default=False, help_text='Test Boolean', verbose_name='Test Boolean'),
        ),
        migrations.AddField(
            model_name='settings',
            name='test_choice',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='', help_text='Test Choice', max_length=999, verbose_name='Test Choice'),
        ),
        migrations.AddField(
            model_name='settings',
            name='test_number',
            field=models.IntegerField(default=0, help_text='Test Number', verbose_name='Test Number'),
        ),
        migrations.AddField(
            model_name='settings',
            name='text_string',
            field=models.CharField(blank=True, default='', help_text='Test String', max_length=999, verbose_name='Test String'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='favorite_events',
            field=models.JSONField(blank=True, default=list, help_text="The user's favorite events, pinned to the top of their event list", verbose_name='Favorite Events'),
        ),
    ]
