# Generated by Django 5.1.2 on 2025-06-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_settings_test_bool_settings_test_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='test_bool',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='test_choice',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='test_number',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='text_string',
        ),
        migrations.AlterField(
            model_name='settings',
            name='favorite_events',
            field=models.JSONField(blank=True, default=list, editable=False, help_text="The user's favorite events, pinned to the top of their event list", verbose_name='Favorite Events'),
        ),
    ]
