# Generated by Django 5.1.2 on 2025-08-07 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_settings_test_bool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=999, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_number',
            field=models.CharField(max_length=6, verbose_name='Team Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Verification Code'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='User UUID'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
