/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import * as zod from 'zod';


/**
 * Begin the passkey registration process
 *
 * Requires either verification_code_uuid or passkey_uuid to verify the user's identity, unless the account is less than PASSKEY_NO_VERIFICATION_MINUTES minutes old
 * @summary Create Passkey
 */
export const CreatePasskeyPasskeysRegisterCreatePostQueryParams = zod.object({
  "verification_code_uuid": zod.union([zod.uuid(),zod.null()]).optional(),
  "passkey_uuid": zod.union([zod.uuid(),zod.null()]).optional()
})

export const CreatePasskeyPasskeysRegisterCreatePostResponse = zod.unknown()

/**
 * Verify the passkey registration
 * @summary Verify Passkey
 */
export const VerifyPasskeyPasskeysRegisterVerifyPostQueryParams = zod.object({
  "challenge_uuid": zod.uuid(),
  "label": zod.string()
})

export const VerifyPasskeyPasskeysRegisterVerifyPostBody = zod.record(zod.string(), zod.unknown())

export const VerifyPasskeyPasskeysRegisterVerifyPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Begin the passkey login process
 * @summary Create Login Passkey
 */
export const CreateLoginPasskeyPasskeysLoginCreatePostResponse = zod.unknown()

/**
 * Verify the passkey login
 * @summary Verify Login Passkey
 */
export const VerifyLoginPasskeyPasskeysLoginVerifyPostQueryParams = zod.object({
  "challenge_uuid": zod.uuid()
})

export const VerifyLoginPasskeyPasskeysLoginVerifyPostBody = zod.record(zod.string(), zod.unknown())

export const VerifyLoginPasskeyPasskeysLoginVerifyPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Begin the passkey verification process
 * @summary Create Verification Passkey
 */
export const CreateVerificationPasskeyPasskeysVerificationCreatePostQueryParams = zod.object({
  "email": zod.string()
})

export const CreateVerificationPasskeyPasskeysVerificationCreatePostResponse = zod.unknown()

/**
 * Verify the passkey verification
 * @summary Verify Verification Passkey
 */
export const VerifyVerificationPasskeyPasskeysVerificationVerifyPostQueryParams = zod.object({
  "challenge_uuid": zod.uuid(),
  "email": zod.string()
})

export const VerifyVerificationPasskeyPasskeysVerificationVerifyPostBody = zod.record(zod.string(), zod.unknown())

export const VerifyVerificationPasskeyPasskeysVerificationVerifyPostResponse = zod.object({
  "message": zod.string()
})

/**
 * Get the passkeys for the current user
 * @summary Get Passkeys
 */
export const GetPasskeysPasskeysGetGetResponseItem = zod.object({
  "uuid": zod.uuid(),
  "label": zod.union([zod.string(),zod.null()]),
  "created_at": zod.iso.datetime({"offset":true})
})
export const GetPasskeysPasskeysGetGetResponse = zod.array(GetPasskeysPasskeysGetGetResponseItem)

/**
 * Delete a passkey on the server
 *
 * Parameters:
 *     uuid (uuid): The uuid of the passkey to delete
 *
 * Returns:
 *     MessageResponse: A message indicating that the passkey was deleted
 * @summary Delete Passkey
 */
export const DeletePasskeyPasskeysDeleteUuidDeleteParams = zod.object({
  "uuid": zod.uuid()
})

export const DeletePasskeyPasskeysDeleteUuidDeleteResponse = zod.object({
  "message": zod.string()
})

