/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type {
  HTTPValidationError,
  MessageResponse,
  NotificationRequest,
  NotificationResponse
} from '../model';

import { customInstance } from '.././client';

export type getNotificationsNotificationsGetResponse200 = {
  data: NotificationResponse[]
  status: 200
}

export type getNotificationsNotificationsGetResponseSuccess = (getNotificationsNotificationsGetResponse200) & {
  headers: Headers;
};
;

export type getNotificationsNotificationsGetResponse = (getNotificationsNotificationsGetResponseSuccess)

export const getGetNotificationsNotificationsGetUrl = () => {




  return `/notifications`
}

/**
 * Get all notifications for the current user

Requires user authentication

Returns:
    list[Notification]: A list of all notifications
 * @summary Get Notifications
 */
export const getNotificationsNotificationsGet = async ( options?: RequestInit): Promise<getNotificationsNotificationsGetResponse> => {

  return customInstance<getNotificationsNotificationsGetResponse>(getGetNotificationsNotificationsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteNotificationNotificationsDeleteNotificationUuidDeleteResponseSuccess = (deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse200) & {
  headers: Headers;
};
export type deleteNotificationNotificationsDeleteNotificationUuidDeleteResponseError = (deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse422) & {
  headers: Headers;
};

export type deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse = (deleteNotificationNotificationsDeleteNotificationUuidDeleteResponseSuccess | deleteNotificationNotificationsDeleteNotificationUuidDeleteResponseError)

export const getDeleteNotificationNotificationsDeleteNotificationUuidDeleteUrl = (notificationUuid: string,) => {




  return `/notifications/delete/${notificationUuid}`
}

/**
 * Delete a notification

Requires user authentication

Parameters:
    notification_uuid (`UUID`): The UUID of the notification to delete

Returns:
    MessageResponse: A message indicating that the notification was deleted
 * @summary Delete Notification
 */
export const deleteNotificationNotificationsDeleteNotificationUuidDelete = async (notificationUuid: string, options?: RequestInit): Promise<deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse> => {

  return customInstance<deleteNotificationNotificationsDeleteNotificationUuidDeleteResponse>(getDeleteNotificationNotificationsDeleteNotificationUuidDeleteUrl(notificationUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse200 = {
  data: MessageResponse
  status: 200
}

export type setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type setNotificationReadNotificationsSetReadNotificationUuidReadPutResponseSuccess = (setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse200) & {
  headers: Headers;
};
export type setNotificationReadNotificationsSetReadNotificationUuidReadPutResponseError = (setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse422) & {
  headers: Headers;
};

export type setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse = (setNotificationReadNotificationsSetReadNotificationUuidReadPutResponseSuccess | setNotificationReadNotificationsSetReadNotificationUuidReadPutResponseError)

export const getSetNotificationReadNotificationsSetReadNotificationUuidReadPutUrl = (notificationUuid: string,
    read: boolean,) => {




  return `/notifications/set_read/${notificationUuid}/${read}`
}

/**
 * Mark a notification as read or unread

Requires user authentication

Parameters:
    notification_uuid (`UUID`): The UUID of the notification to mark as read
    read (`bool`): The read status of the notification

Returns:
    MessageResponse: A message indicating that the notification was marked as read or unread
 * @summary Set Notification Read
 */
export const setNotificationReadNotificationsSetReadNotificationUuidReadPut = async (notificationUuid: string,
    read: boolean, options?: RequestInit): Promise<setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse> => {

  return customInstance<setNotificationReadNotificationsSetReadNotificationUuidReadPutResponse>(getSetNotificationReadNotificationsSetReadNotificationUuidReadPutUrl(notificationUuid,read),
  {
    ...options,
    method: 'PUT'


  }
);}


export type addNotificationNotificationsSendPostResponse200 = {
  data: NotificationResponse | MessageResponse
  status: 200
}

export type addNotificationNotificationsSendPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type addNotificationNotificationsSendPostResponseSuccess = (addNotificationNotificationsSendPostResponse200) & {
  headers: Headers;
};
export type addNotificationNotificationsSendPostResponseError = (addNotificationNotificationsSendPostResponse422) & {
  headers: Headers;
};

export type addNotificationNotificationsSendPostResponse = (addNotificationNotificationsSendPostResponseSuccess | addNotificationNotificationsSendPostResponseError)

export const getAddNotificationNotificationsSendPostUrl = () => {




  return `/notifications/send`
}

/**
 * Add a notification to the database

This is used when the client creates a notification that needs to be synced to the server

Requires user authentication

Parameters:
    data (`NotificationRequest`): The data to create the notification with

Returns:
    NotificationResponse: The notification that was created
 * @summary Add Notification
 */
export const addNotificationNotificationsSendPost = async (notificationRequest: NotificationRequest, options?: RequestInit): Promise<addNotificationNotificationsSendPostResponse> => {

  return customInstance<addNotificationNotificationsSendPostResponse>(getAddNotificationNotificationsSendPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notificationRequest,)
  }
);}


