/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MessageResponse,
  OrganizationMemberResponse,
  OrganizationResponse
} from '.././model';


export const getCreateOrganizationOrganizationCreatePostResponseMock = (overrideResponse: Partial< OrganizationResponse > = {}): OrganizationResponse => ({uuid: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetOrganizationsOrganizationAllListGetResponseMock = (): OrganizationResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getGetUserOrganizationsOrganizationMeListGetResponseMock = (): OrganizationResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getGetOrganizationOrganizationOrganizationUuidGetResponseMock = (overrideResponse: Partial< OrganizationResponse > = {}): OrganizationResponse => ({uuid: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getDeleteOrganizationOrganizationDeleteOrganizationUuidDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetOrganizationMembersOrganizationOrganizationUuidMembersGetResponseMock = (): OrganizationMemberResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), organization: faker.string.uuid(), user: faker.string.uuid(), role: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))


export const getCreateOrganizationOrganizationCreatePostMockHandler = (overrideResponse?: OrganizationResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<OrganizationResponse> | OrganizationResponse), options?: RequestHandlerOptions) => {
  return http.post('*/organization/create', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateOrganizationOrganizationCreatePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetOrganizationsOrganizationAllListGetMockHandler = (overrideResponse?: OrganizationResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrganizationResponse[]> | OrganizationResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/organization/all/list', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOrganizationsOrganizationAllListGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetUserOrganizationsOrganizationMeListGetMockHandler = (overrideResponse?: OrganizationResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrganizationResponse[]> | OrganizationResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/organization/me/list', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserOrganizationsOrganizationMeListGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetOrganizationOrganizationOrganizationUuidGetMockHandler = (overrideResponse?: OrganizationResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrganizationResponse> | OrganizationResponse), options?: RequestHandlerOptions) => {
  return http.get('*/organization/:organizationUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOrganizationOrganizationOrganizationUuidGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteOrganizationOrganizationDeleteOrganizationUuidDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/organization/delete/:organizationUuid', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteOrganizationOrganizationDeleteOrganizationUuidDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetOrganizationMembersOrganizationOrganizationUuidMembersGetMockHandler = (overrideResponse?: OrganizationMemberResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OrganizationMemberResponse[]> | OrganizationMemberResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/organization/:organizationUuid/members', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOrganizationMembersOrganizationOrganizationUuidMembersGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getOrganizationsMock = () => [
  getCreateOrganizationOrganizationCreatePostMockHandler(),
  getGetOrganizationsOrganizationAllListGetMockHandler(),
  getGetUserOrganizationsOrganizationMeListGetMockHandler(),
  getGetOrganizationOrganizationOrganizationUuidGetMockHandler(),
  getDeleteOrganizationOrganizationDeleteOrganizationUuidDeleteMockHandler(),
  getGetOrganizationMembersOrganizationOrganizationUuidMembersGetMockHandler()
]
