# Generated by Django 5.1.2 on 2025-08-07 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_uuid_to_pit_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='account',
            field=models.BooleanField(default=False, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='data',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='data',
            name='event',
            field=models.CharField(max_length=999, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='data',
            name='event_code',
            field=models.CharField(blank=True, max_length=99, verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='data',
            name='event_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='data',
            name='team_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Team Number'),
        ),
        migrations.AlterField(
            model_name='data',
            name='team_number_created',
            field=models.CharField(blank=True, max_length=6, verbose_name='Team Number Created'),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Created'),
        ),
        migrations.AlterField(
            model_name='data',
            name='username_created',
            field=models.CharField(blank=True, max_length=999, verbose_name='Username Created'),
        ),
        migrations.AlterField(
            model_name='data',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025')], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='Custom'),
        ),
        migrations.AlterField(
            model_name='event',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=99, verbose_name='Event Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=999, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025')], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='data',
            field=models.JSONField(default=list, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='nickname',
            field=models.CharField(blank=True, max_length=999, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='pit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pitgroup', verbose_name='Pit Group'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='team_number',
            field=models.CharField(max_length=6, verbose_name='Team Number'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='pitgroup',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='pitgroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='pitgroup',
            name='events_generated',
            field=models.BooleanField(default=False, verbose_name='Events Generated'),
        ),
    ]
