# Generated by Django 5.2.6 on 2025-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_data_account_alter_data_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitgroup',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2024, '2024'), (2025, '2025')], null=True, verbose_name='Year'),
        ),
    ]
