# Generated by Django 5.2.6 on 2025-09-14 19:22

from django.db import migrations, models


def copy_year_from_event(apps, schema_editor):
    PitGroup = apps.get_model("main", "PitGroup")
    for pit_group in PitGroup.objects.all():
        pit_group.year = pit_group.event.year
        pit_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_pitgroup_year"),
    ]

    operations = [
        migrations.RunPython(copy_year_from_event, migrations.RunPython.noop),
    ]
