# Generated by Django 5.2.6 on 2025-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_add_year_to_pit_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitgroup',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025')], verbose_name='Year'),
        ),
    ]
