/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  BaseSettings,
  MessageResponse,
  TokenResponse,
  UserResponse
} from '.././model';


export const getSignupAuthSignupPostResponseMock = (overrideResponse: Partial< TokenResponse > = {}): TokenResponse => ({access_token: faker.string.alpha({length: {min: 10, max: 20}}), token_type: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getLoginForAccessTokenTokenPostResponseMock = (overrideResponse: Partial< TokenResponse > = {}): TokenResponse => ({access_token: faker.string.alpha({length: {min: 10, max: 20}}), token_type: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getGetUsersUsersGetResponseMock = (): UserResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({uuid: faker.string.uuid(), username: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), is_superuser: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getDeleteUserUsersDeleteUsernameDeleteResponseMock = (overrideResponse: Partial< MessageResponse > = {}): MessageResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetUserSettingsUsersMeGetSettingsGetResponseMock = (overrideResponse: Partial< BaseSettings > = {}): BaseSettings => ({favorite_events: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getUpdateUserSettingsUsersMeUpdateSettingsPostResponseMock = (overrideResponse: Partial< BaseSettings > = {}): BaseSettings => ({favorite_events: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getSetSuperuserUsersSetSuperuserUsernamePostResponseMock = (overrideResponse: Partial< UserResponse > = {}): UserResponse => ({uuid: faker.string.uuid(), username: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), is_superuser: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getValidateUserAuthValidateGetResponseMock = (overrideResponse: Partial< UserResponse > = {}): UserResponse => ({uuid: faker.string.uuid(), username: faker.string.alpha({length: {min: 10, max: 20}}), email: faker.internet.email(), is_superuser: faker.datatype.boolean(), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getSignupAuthSignupPostMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/auth/signup', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSignupAuthSignupPostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getLoginForAccessTokenTokenPostMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/token', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginForAccessTokenTokenPostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetUsersUsersGetMockHandler = (overrideResponse?: UserResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserResponse[]> | UserResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/users/', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUsersUsersGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteUserUsersDeleteUsernameDeleteMockHandler = (overrideResponse?: MessageResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<MessageResponse> | MessageResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/users/delete/:username', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteUserUsersDeleteUsernameDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetUserSettingsUsersMeGetSettingsGetMockHandler = (overrideResponse?: BaseSettings | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BaseSettings> | BaseSettings), options?: RequestHandlerOptions) => {
  return http.get('*/users/me/get_settings', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserSettingsUsersMeGetSettingsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateUserSettingsUsersMeUpdateSettingsPostMockHandler = (overrideResponse?: BaseSettings | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<BaseSettings> | BaseSettings), options?: RequestHandlerOptions) => {
  return http.post('*/users/me/update_settings', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateUserSettingsUsersMeUpdateSettingsPostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSetSuperuserUsersSetSuperuserUsernamePostMockHandler = (overrideResponse?: UserResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserResponse> | UserResponse), options?: RequestHandlerOptions) => {
  return http.post('*/users/set_superuser/:username', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSetSuperuserUsersSetSuperuserUsernamePostResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getValidateUserAuthValidateGetMockHandler = (overrideResponse?: UserResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserResponse> | UserResponse), options?: RequestHandlerOptions) => {
  return http.get('*/auth/validate', async (info) => {
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getValidateUserAuthValidateGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAuthMock = () => [
  getSignupAuthSignupPostMockHandler(),
  getLoginForAccessTokenTokenPostMockHandler(),
  getGetUsersUsersGetMockHandler(),
  getDeleteUserUsersDeleteUsernameDeleteMockHandler(),
  getGetUserSettingsUsersMeGetSettingsGetMockHandler(),
  getUpdateUserSettingsUsersMeUpdateSettingsPostMockHandler(),
  getSetSuperuserUsersSetSuperuserUsernamePostMockHandler(),
  getValidateUserAuthValidateGetMockHandler()
]
