/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import type {
  BaseSettings,
  BodyLoginAuthLoginPost,
  CheckUniqueUsernameAuthCheckUniqueUsernameGetParams,
  CreateVerificationCodeAuthCreateVerificationCodePostParams,
  ForgotPasswordRequest,
  HTTPValidationError,
  MessageResponse,
  SetDisplayNameUsersMeSetDisplayNamePostParams,
  SetTeamNumberUsersMeSetTeamNumberPostParams,
  SignupRequest,
  UserMeResponse,
  UserResponse,
  UserSetting,
  VerifyVerificationCodeRequest,
  VerifyVerificationCodeResponse
} from '../model';

import { customInstance } from '.././client';

export type meAuthMeGetResponse200 = {
  data: UserMeResponse
  status: 200
}

export type meAuthMeGetResponseSuccess = (meAuthMeGetResponse200) & {
  headers: Headers;
};
;

export type meAuthMeGetResponse = (meAuthMeGetResponseSuccess)

export const getMeAuthMeGetUrl = () => {




  return `/auth/me`
}

/**
 * Validates the current user, and returns their details

Returns:
    UserMeResponse: The current user details, and whether they are authenticated or not
 * @summary Me
 */
export const meAuthMeGet = async ( options?: RequestInit): Promise<meAuthMeGetResponse> => {

  return customInstance<meAuthMeGetResponse>(getMeAuthMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type loginAuthLoginPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginAuthLoginPostResponseSuccess = (loginAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginAuthLoginPostResponseError = (loginAuthLoginPostResponse422) & {
  headers: Headers;
};

export type loginAuthLoginPostResponse = (loginAuthLoginPostResponseSuccess | loginAuthLoginPostResponseError)

export const getLoginAuthLoginPostUrl = () => {




  return `/auth/login`
}

/**
 * Logs in a user

Returns:
    MessageResponse: A message indicating that the user has been logged in
 * @summary Login
 */
export const loginAuthLoginPost = async (bodyLoginAuthLoginPost: BodyLoginAuthLoginPost, options?: RequestInit): Promise<loginAuthLoginPostResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyLoginAuthLoginPost.grant_type !== undefined && bodyLoginAuthLoginPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAuthLoginPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginAuthLoginPost.username);
formUrlEncoded.append(`password`, bodyLoginAuthLoginPost.password);
if(bodyLoginAuthLoginPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAuthLoginPost.scope);
 }
if(bodyLoginAuthLoginPost.client_id !== undefined && bodyLoginAuthLoginPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAuthLoginPost.client_id);
 }
if(bodyLoginAuthLoginPost.client_secret !== undefined && bodyLoginAuthLoginPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAuthLoginPost.client_secret);
 }

  return customInstance<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
);}


export type signupAuthSignupPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type signupAuthSignupPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type signupAuthSignupPostResponseSuccess = (signupAuthSignupPostResponse200) & {
  headers: Headers;
};
export type signupAuthSignupPostResponseError = (signupAuthSignupPostResponse422) & {
  headers: Headers;
};

export type signupAuthSignupPostResponse = (signupAuthSignupPostResponseSuccess | signupAuthSignupPostResponseError)

export const getSignupAuthSignupPostUrl = () => {




  return `/auth/signup`
}

/**
 * Create a new user

If this is the first user on the server, make them a superuser

TODO: email_verified status probably shouldn't come from the client, and should instead be verified by the server to prevent verified spoofing

Paramaters:
    data (SignupRequest): The data to create the user

Returns:
    MessageResponse: A message indicating that the user has been created
 * @summary Signup
 */
export const signupAuthSignupPost = async (signupRequest: SignupRequest, options?: RequestInit): Promise<signupAuthSignupPostResponse> => {

  return customInstance<signupAuthSignupPostResponse>(getSignupAuthSignupPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupRequest,)
  }
);}


export type logoutAuthLogoutPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type logoutAuthLogoutPostResponseSuccess = (logoutAuthLogoutPostResponse200) & {
  headers: Headers;
};
;

export type logoutAuthLogoutPostResponse = (logoutAuthLogoutPostResponseSuccess)

export const getLogoutAuthLogoutPostUrl = () => {




  return `/auth/logout`
}

/**
 * Logs out a user
 * @summary Logout
 */
export const logoutAuthLogoutPost = async ( options?: RequestInit): Promise<logoutAuthLogoutPostResponse> => {

  return customInstance<logoutAuthLogoutPostResponse>(getLogoutAuthLogoutPostUrl(),
  {
    ...options,
    method: 'POST'


  }
);}


export type getUsersUsersGetResponse200 = {
  data: UserResponse[]
  status: 200
}

export type getUsersUsersGetResponseSuccess = (getUsersUsersGetResponse200) & {
  headers: Headers;
};
;

export type getUsersUsersGetResponse = (getUsersUsersGetResponseSuccess)

export const getGetUsersUsersGetUrl = () => {




  return `/users/`
}

/**
 * Get all users on the server

Requires superuser access

Returns:
    list[User]: A list of all users
 * @summary Get Users
 */
export const getUsersUsersGet = async ( options?: RequestInit): Promise<getUsersUsersGetResponse> => {

  return customInstance<getUsersUsersGetResponse>(getGetUsersUsersGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type deleteUserUsersDeleteUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteUserUsersDeleteUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteUserUsersDeleteUuidDeleteResponseSuccess = (deleteUserUsersDeleteUuidDeleteResponse200) & {
  headers: Headers;
};
export type deleteUserUsersDeleteUuidDeleteResponseError = (deleteUserUsersDeleteUuidDeleteResponse422) & {
  headers: Headers;
};

export type deleteUserUsersDeleteUuidDeleteResponse = (deleteUserUsersDeleteUuidDeleteResponseSuccess | deleteUserUsersDeleteUuidDeleteResponseError)

export const getDeleteUserUsersDeleteUuidDeleteUrl = (uuid: string,) => {




  return `/users/delete/${uuid}`
}

/**
 * Delete a user on the server

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to delete

Returns:
    MessageResponse: A message indicating that the user was deleted
 * @summary Delete User
 */
export const deleteUserUsersDeleteUuidDelete = async (uuid: string, options?: RequestInit): Promise<deleteUserUsersDeleteUuidDeleteResponse> => {

  return customInstance<deleteUserUsersDeleteUuidDeleteResponse>(getDeleteUserUsersDeleteUuidDeleteUrl(uuid),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type getUserSettingsUsersMeGetSettingsGetResponse200 = {
  data: UserSetting[]
  status: 200
}

export type getUserSettingsUsersMeGetSettingsGetResponseSuccess = (getUserSettingsUsersMeGetSettingsGetResponse200) & {
  headers: Headers;
};
;

export type getUserSettingsUsersMeGetSettingsGetResponse = (getUserSettingsUsersMeGetSettingsGetResponseSuccess)

export const getGetUserSettingsUsersMeGetSettingsGetUrl = () => {




  return `/users/me/get_settings`
}

/**
 * Get the settings for the current user

Returns:
    BaseSettings: The settings for the current user
 * @summary Get User Settings
 */
export const getUserSettingsUsersMeGetSettingsGet = async ( options?: RequestInit): Promise<getUserSettingsUsersMeGetSettingsGetResponse> => {

  return customInstance<getUserSettingsUsersMeGetSettingsGetResponse>(getGetUserSettingsUsersMeGetSettingsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type updateUserSettingsUsersMeUpdateSettingsPostResponse200 = {
  data: BaseSettings
  status: 200
}

export type updateUserSettingsUsersMeUpdateSettingsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateUserSettingsUsersMeUpdateSettingsPostResponseSuccess = (updateUserSettingsUsersMeUpdateSettingsPostResponse200) & {
  headers: Headers;
};
export type updateUserSettingsUsersMeUpdateSettingsPostResponseError = (updateUserSettingsUsersMeUpdateSettingsPostResponse422) & {
  headers: Headers;
};

export type updateUserSettingsUsersMeUpdateSettingsPostResponse = (updateUserSettingsUsersMeUpdateSettingsPostResponseSuccess | updateUserSettingsUsersMeUpdateSettingsPostResponseError)

export const getUpdateUserSettingsUsersMeUpdateSettingsPostUrl = () => {




  return `/users/me/update_settings`
}

/**
 * Update the settings for the current user

Parameters:
    data (BaseSettings): The settings to update

Returns:
    BaseSettings: The settings for the current user
 * @summary Update User Settings
 */
export const updateUserSettingsUsersMeUpdateSettingsPost = async (baseSettings: BaseSettings, options?: RequestInit): Promise<updateUserSettingsUsersMeUpdateSettingsPostResponse> => {

  return customInstance<updateUserSettingsUsersMeUpdateSettingsPostResponse>(getUpdateUserSettingsUsersMeUpdateSettingsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      baseSettings,)
  }
);}


export type setSuperuserUsersSetSuperuserUuidPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type setSuperuserUsersSetSuperuserUuidPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type setSuperuserUsersSetSuperuserUuidPostResponseSuccess = (setSuperuserUsersSetSuperuserUuidPostResponse200) & {
  headers: Headers;
};
export type setSuperuserUsersSetSuperuserUuidPostResponseError = (setSuperuserUsersSetSuperuserUuidPostResponse422) & {
  headers: Headers;
};

export type setSuperuserUsersSetSuperuserUuidPostResponse = (setSuperuserUsersSetSuperuserUuidPostResponseSuccess | setSuperuserUsersSetSuperuserUuidPostResponseError)

export const getSetSuperuserUsersSetSuperuserUuidPostUrl = (uuid: string,) => {




  return `/users/set_superuser/${uuid}`
}

/**
 * Set a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to set as a superuser

Returns:
    User: The user that was set as a superuser
 * @summary Set Superuser
 */
export const setSuperuserUsersSetSuperuserUuidPost = async (uuid: string, options?: RequestInit): Promise<setSuperuserUsersSetSuperuserUuidPostResponse> => {

  return customInstance<setSuperuserUsersSetSuperuserUuidPostResponse>(getSetSuperuserUsersSetSuperuserUuidPostUrl(uuid),
  {
    ...options,
    method: 'POST'


  }
);}


export type removeSuperuserUsersRemoveSuperuserUuidPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type removeSuperuserUsersRemoveSuperuserUuidPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type removeSuperuserUsersRemoveSuperuserUuidPostResponseSuccess = (removeSuperuserUsersRemoveSuperuserUuidPostResponse200) & {
  headers: Headers;
};
export type removeSuperuserUsersRemoveSuperuserUuidPostResponseError = (removeSuperuserUsersRemoveSuperuserUuidPostResponse422) & {
  headers: Headers;
};

export type removeSuperuserUsersRemoveSuperuserUuidPostResponse = (removeSuperuserUsersRemoveSuperuserUuidPostResponseSuccess | removeSuperuserUsersRemoveSuperuserUuidPostResponseError)

export const getRemoveSuperuserUsersRemoveSuperuserUuidPostUrl = (uuid: string,) => {




  return `/users/remove_superuser/${uuid}`
}

/**
 * Remove a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to remove as a superuser

Returns:
    User: The user that was removed as a superuser
 * @summary Remove Superuser
 */
export const removeSuperuserUsersRemoveSuperuserUuidPost = async (uuid: string, options?: RequestInit): Promise<removeSuperuserUsersRemoveSuperuserUuidPostResponse> => {

  return customInstance<removeSuperuserUsersRemoveSuperuserUuidPostResponse>(getRemoveSuperuserUsersRemoveSuperuserUuidPostUrl(uuid),
  {
    ...options,
    method: 'POST'


  }
);}


export type setDisplayNameUsersMeSetDisplayNamePostResponse200 = {
  data: MessageResponse
  status: 200
}

export type setDisplayNameUsersMeSetDisplayNamePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type setDisplayNameUsersMeSetDisplayNamePostResponseSuccess = (setDisplayNameUsersMeSetDisplayNamePostResponse200) & {
  headers: Headers;
};
export type setDisplayNameUsersMeSetDisplayNamePostResponseError = (setDisplayNameUsersMeSetDisplayNamePostResponse422) & {
  headers: Headers;
};

export type setDisplayNameUsersMeSetDisplayNamePostResponse = (setDisplayNameUsersMeSetDisplayNamePostResponseSuccess | setDisplayNameUsersMeSetDisplayNamePostResponseError)

export const getSetDisplayNameUsersMeSetDisplayNamePostUrl = (params: SetDisplayNameUsersMeSetDisplayNamePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/me/set_display_name?${stringifiedParams}` : `/users/me/set_display_name`
}

/**
 * Set the display name for the current user

Parameters:
    display_name (str): The display name to set

Returns:
    MessageResponse: A message indicating that the display name was set
 * @summary Set Display Name
 */
export const setDisplayNameUsersMeSetDisplayNamePost = async (params: SetDisplayNameUsersMeSetDisplayNamePostParams, options?: RequestInit): Promise<setDisplayNameUsersMeSetDisplayNamePostResponse> => {

  return customInstance<setDisplayNameUsersMeSetDisplayNamePostResponse>(getSetDisplayNameUsersMeSetDisplayNamePostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}


export type setTeamNumberUsersMeSetTeamNumberPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type setTeamNumberUsersMeSetTeamNumberPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type setTeamNumberUsersMeSetTeamNumberPostResponseSuccess = (setTeamNumberUsersMeSetTeamNumberPostResponse200) & {
  headers: Headers;
};
export type setTeamNumberUsersMeSetTeamNumberPostResponseError = (setTeamNumberUsersMeSetTeamNumberPostResponse422) & {
  headers: Headers;
};

export type setTeamNumberUsersMeSetTeamNumberPostResponse = (setTeamNumberUsersMeSetTeamNumberPostResponseSuccess | setTeamNumberUsersMeSetTeamNumberPostResponseError)

export const getSetTeamNumberUsersMeSetTeamNumberPostUrl = (params: SetTeamNumberUsersMeSetTeamNumberPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/me/set_team_number?${stringifiedParams}` : `/users/me/set_team_number`
}

/**
 * Set the team number for the current user

Parameters:
    team_number (int): The team number to set

Returns:
    MessageResponse: A message indicating that the team number was set
 * @summary Set Team Number
 */
export const setTeamNumberUsersMeSetTeamNumberPost = async (params: SetTeamNumberUsersMeSetTeamNumberPostParams, options?: RequestInit): Promise<setTeamNumberUsersMeSetTeamNumberPostResponse> => {

  return customInstance<setTeamNumberUsersMeSetTeamNumberPostResponse>(getSetTeamNumberUsersMeSetTeamNumberPostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}


export type checkUniqueUsernameAuthCheckUniqueUsernameGetResponse200 = {
  data: unknown
  status: 200
}

export type checkUniqueUsernameAuthCheckUniqueUsernameGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type checkUniqueUsernameAuthCheckUniqueUsernameGetResponseSuccess = (checkUniqueUsernameAuthCheckUniqueUsernameGetResponse200) & {
  headers: Headers;
};
export type checkUniqueUsernameAuthCheckUniqueUsernameGetResponseError = (checkUniqueUsernameAuthCheckUniqueUsernameGetResponse422) & {
  headers: Headers;
};

export type checkUniqueUsernameAuthCheckUniqueUsernameGetResponse = (checkUniqueUsernameAuthCheckUniqueUsernameGetResponseSuccess | checkUniqueUsernameAuthCheckUniqueUsernameGetResponseError)

export const getCheckUniqueUsernameAuthCheckUniqueUsernameGetUrl = (params: CheckUniqueUsernameAuthCheckUniqueUsernameGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/check_unique_username?${stringifiedParams}` : `/auth/check_unique_username`
}

/**
 * Check if a username and email is unique

Parameters:
    username (str): The username to check
    email (str): The email to check

Returns:
    MessageResponse: A message indicating whether the username is unique
 * @summary Check Unique Username
 */
export const checkUniqueUsernameAuthCheckUniqueUsernameGet = async (params: CheckUniqueUsernameAuthCheckUniqueUsernameGetParams, options?: RequestInit): Promise<checkUniqueUsernameAuthCheckUniqueUsernameGetResponse> => {

  return customInstance<checkUniqueUsernameAuthCheckUniqueUsernameGetResponse>(getCheckUniqueUsernameAuthCheckUniqueUsernameGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type createVerificationCodeAuthCreateVerificationCodePostResponse200 = {
  data: unknown
  status: 200
}

export type createVerificationCodeAuthCreateVerificationCodePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createVerificationCodeAuthCreateVerificationCodePostResponseSuccess = (createVerificationCodeAuthCreateVerificationCodePostResponse200) & {
  headers: Headers;
};
export type createVerificationCodeAuthCreateVerificationCodePostResponseError = (createVerificationCodeAuthCreateVerificationCodePostResponse422) & {
  headers: Headers;
};

export type createVerificationCodeAuthCreateVerificationCodePostResponse = (createVerificationCodeAuthCreateVerificationCodePostResponseSuccess | createVerificationCodeAuthCreateVerificationCodePostResponseError)

export const getCreateVerificationCodeAuthCreateVerificationCodePostUrl = (params: CreateVerificationCodeAuthCreateVerificationCodePostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/create_verification_code?${stringifiedParams}` : `/auth/create_verification_code`
}

/**
 * Given an email, create a verification code and send it to the user

If an identity is found, attach the user to the verification code

Parameters:
    email (str): The email to create a verification code for
 * @summary Create Verification Code
 */
export const createVerificationCodeAuthCreateVerificationCodePost = async (params: CreateVerificationCodeAuthCreateVerificationCodePostParams, options?: RequestInit): Promise<createVerificationCodeAuthCreateVerificationCodePostResponse> => {

  return customInstance<createVerificationCodeAuthCreateVerificationCodePostResponse>(getCreateVerificationCodeAuthCreateVerificationCodePostUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}


export type verifyVerificationCodeAuthVerifyVerificationCodePostResponse200 = {
  data: VerifyVerificationCodeResponse
  status: 200
}

export type verifyVerificationCodeAuthVerifyVerificationCodePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type verifyVerificationCodeAuthVerifyVerificationCodePostResponseSuccess = (verifyVerificationCodeAuthVerifyVerificationCodePostResponse200) & {
  headers: Headers;
};
export type verifyVerificationCodeAuthVerifyVerificationCodePostResponseError = (verifyVerificationCodeAuthVerifyVerificationCodePostResponse422) & {
  headers: Headers;
};

export type verifyVerificationCodeAuthVerifyVerificationCodePostResponse = (verifyVerificationCodeAuthVerifyVerificationCodePostResponseSuccess | verifyVerificationCodeAuthVerifyVerificationCodePostResponseError)

export const getVerifyVerificationCodeAuthVerifyVerificationCodePostUrl = () => {




  return `/auth/verify_verification_code`
}

/**
 * Verify a verification code for a user

Given an email and a verification code, verify the verification code

If an identity is found, the verification code must be attached to the user to be validated.
    This would occour when verifying an email from the profile page when their email was not yet verified.
    When doing this, also set that user's email_verified to be true if it is not already.

The code's created_at should be less than VERIFICATION_CODE_EXPIRE_MINUTES to be validated.

Parameters:
    email (str): The email to verify the verification code for
    code (int): The verification code to verify
 * @summary Verify Verification Code
 */
export const verifyVerificationCodeAuthVerifyVerificationCodePost = async (verifyVerificationCodeRequest: VerifyVerificationCodeRequest, options?: RequestInit): Promise<verifyVerificationCodeAuthVerifyVerificationCodePostResponse> => {

  return customInstance<verifyVerificationCodeAuthVerifyVerificationCodePostResponse>(getVerifyVerificationCodeAuthVerifyVerificationCodePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyVerificationCodeRequest,)
  }
);}


export type forgotPasswordAuthForgotPasswordPostResponse200 = {
  data: MessageResponse
  status: 200
}

export type forgotPasswordAuthForgotPasswordPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type forgotPasswordAuthForgotPasswordPostResponseSuccess = (forgotPasswordAuthForgotPasswordPostResponse200) & {
  headers: Headers;
};
export type forgotPasswordAuthForgotPasswordPostResponseError = (forgotPasswordAuthForgotPasswordPostResponse422) & {
  headers: Headers;
};

export type forgotPasswordAuthForgotPasswordPostResponse = (forgotPasswordAuthForgotPasswordPostResponseSuccess | forgotPasswordAuthForgotPasswordPostResponseError)

export const getForgotPasswordAuthForgotPasswordPostUrl = () => {




  return `/auth/forgot_password`
}

/**
 * Given an email, password, and verification code UUID, change the password for a user

First, confirm that the verification code is valid. If so, change the password for the user.

Parameters:
    email (str): The email to change the password for
    password (str): The new password
    verification_code_uuid (str): The UUID of the verification code
 * @summary Forgot Password
 */
export const forgotPasswordAuthForgotPasswordPost = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<forgotPasswordAuthForgotPasswordPostResponse> => {

  return customInstance<forgotPasswordAuthForgotPasswordPostResponse>(getForgotPasswordAuthForgotPasswordPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordRequest,)
  }
);}


