/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.0.0-alpha.6
 */
import type {
  BaseSettings,
  BodyLoginForAccessTokenTokenPost,
  HTTPValidationError,
  MessageResponse,
  SignupRequest,
  TokenResponse,
  UserResponse
} from '.././model';

import { customInstance } from '.././client';

/**
 * Create a new user

If this is the first user on the server, make them a superuser

Paramaters:
    data (SignupRequest): The data to create the user

Returns:
    TokenResponse: The access token
 * @summary Signup
 */
export type signupAuthSignupPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type signupAuthSignupPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type signupAuthSignupPostResponseSuccess = (signupAuthSignupPostResponse200) & {
  headers: Headers;
};
export type signupAuthSignupPostResponseError = (signupAuthSignupPostResponse422) & {
  headers: Headers;
};

export type signupAuthSignupPostResponse = (signupAuthSignupPostResponseSuccess | signupAuthSignupPostResponseError)

export const getSignupAuthSignupPostUrl = () => {


  

  return `/auth/signup`
}

export const signupAuthSignupPost = async (signupRequest: SignupRequest, options?: RequestInit): Promise<signupAuthSignupPostResponse> => {
  
  return customInstance<signupAuthSignupPostResponse>(getSignupAuthSignupPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupRequest,)
  }
);}


/**
 * OAuth2 compatible token login, get an access token for future requests

Parameters:
    form_data (OAuth2PasswordRequestForm): The data to login with

Returns:
    dict[str, str]: The access token
 * @summary Login For Access Token
 */
export type loginForAccessTokenTokenPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginForAccessTokenTokenPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type loginForAccessTokenTokenPostResponseSuccess = (loginForAccessTokenTokenPostResponse200) & {
  headers: Headers;
};
export type loginForAccessTokenTokenPostResponseError = (loginForAccessTokenTokenPostResponse422) & {
  headers: Headers;
};

export type loginForAccessTokenTokenPostResponse = (loginForAccessTokenTokenPostResponseSuccess | loginForAccessTokenTokenPostResponseError)

export const getLoginForAccessTokenTokenPostUrl = () => {


  

  return `/token`
}

export const loginForAccessTokenTokenPost = async (bodyLoginForAccessTokenTokenPost: BodyLoginForAccessTokenTokenPost, options?: RequestInit): Promise<loginForAccessTokenTokenPostResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyLoginForAccessTokenTokenPost.grant_type !== undefined && bodyLoginForAccessTokenTokenPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginForAccessTokenTokenPost.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginForAccessTokenTokenPost.username);
formUrlEncoded.append(`password`, bodyLoginForAccessTokenTokenPost.password);
if(bodyLoginForAccessTokenTokenPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginForAccessTokenTokenPost.scope);
 }
if(bodyLoginForAccessTokenTokenPost.client_id !== undefined && bodyLoginForAccessTokenTokenPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginForAccessTokenTokenPost.client_id);
 }
if(bodyLoginForAccessTokenTokenPost.client_secret !== undefined && bodyLoginForAccessTokenTokenPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginForAccessTokenTokenPost.client_secret);
 }

  return customInstance<loginForAccessTokenTokenPostResponse>(getLoginForAccessTokenTokenPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: 
      formUrlEncoded,
  }
);}


/**
 * Get all users on the server

Requires superuser access

Returns:
    list[User]: A list of all users
 * @summary Get Users
 */
export type getUsersUsersGetResponse200 = {
  data: UserResponse[]
  status: 200
}
    
export type getUsersUsersGetResponseSuccess = (getUsersUsersGetResponse200) & {
  headers: Headers;
};
;

export type getUsersUsersGetResponse = (getUsersUsersGetResponseSuccess)

export const getGetUsersUsersGetUrl = () => {


  

  return `/users/`
}

export const getUsersUsersGet = async ( options?: RequestInit): Promise<getUsersUsersGetResponse> => {
  
  return customInstance<getUsersUsersGetResponse>(getGetUsersUsersGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Delete a user on the server

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to delete

Returns:
    MessageResponse: A message indicating that the user was deleted
 * @summary Delete User
 */
export type deleteUserUsersDeleteUuidDeleteResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteUserUsersDeleteUuidDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteUserUsersDeleteUuidDeleteResponseSuccess = (deleteUserUsersDeleteUuidDeleteResponse200) & {
  headers: Headers;
};
export type deleteUserUsersDeleteUuidDeleteResponseError = (deleteUserUsersDeleteUuidDeleteResponse422) & {
  headers: Headers;
};

export type deleteUserUsersDeleteUuidDeleteResponse = (deleteUserUsersDeleteUuidDeleteResponseSuccess | deleteUserUsersDeleteUuidDeleteResponseError)

export const getDeleteUserUsersDeleteUuidDeleteUrl = (uuid: string,) => {


  

  return `/users/delete/${uuid}`
}

export const deleteUserUsersDeleteUuidDelete = async (uuid: string, options?: RequestInit): Promise<deleteUserUsersDeleteUuidDeleteResponse> => {
  
  return customInstance<deleteUserUsersDeleteUuidDeleteResponse>(getDeleteUserUsersDeleteUuidDeleteUrl(uuid),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Get the settings for the current user

Returns:
    BaseSettings: The settings for the current user
 * @summary Get User Settings
 */
export type getUserSettingsUsersMeGetSettingsGetResponse200 = {
  data: BaseSettings
  status: 200
}
    
export type getUserSettingsUsersMeGetSettingsGetResponseSuccess = (getUserSettingsUsersMeGetSettingsGetResponse200) & {
  headers: Headers;
};
;

export type getUserSettingsUsersMeGetSettingsGetResponse = (getUserSettingsUsersMeGetSettingsGetResponseSuccess)

export const getGetUserSettingsUsersMeGetSettingsGetUrl = () => {


  

  return `/users/me/get_settings`
}

export const getUserSettingsUsersMeGetSettingsGet = async ( options?: RequestInit): Promise<getUserSettingsUsersMeGetSettingsGetResponse> => {
  
  return customInstance<getUserSettingsUsersMeGetSettingsGetResponse>(getGetUserSettingsUsersMeGetSettingsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update the settings for the current user

Parameters:
    data (BaseSettings): The settings to update

Returns:
    BaseSettings: The settings for the current user
 * @summary Update User Settings
 */
export type updateUserSettingsUsersMeUpdateSettingsPostResponse200 = {
  data: BaseSettings
  status: 200
}

export type updateUserSettingsUsersMeUpdateSettingsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateUserSettingsUsersMeUpdateSettingsPostResponseSuccess = (updateUserSettingsUsersMeUpdateSettingsPostResponse200) & {
  headers: Headers;
};
export type updateUserSettingsUsersMeUpdateSettingsPostResponseError = (updateUserSettingsUsersMeUpdateSettingsPostResponse422) & {
  headers: Headers;
};

export type updateUserSettingsUsersMeUpdateSettingsPostResponse = (updateUserSettingsUsersMeUpdateSettingsPostResponseSuccess | updateUserSettingsUsersMeUpdateSettingsPostResponseError)

export const getUpdateUserSettingsUsersMeUpdateSettingsPostUrl = () => {


  

  return `/users/me/update_settings`
}

export const updateUserSettingsUsersMeUpdateSettingsPost = async (baseSettings: BaseSettings, options?: RequestInit): Promise<updateUserSettingsUsersMeUpdateSettingsPostResponse> => {
  
  return customInstance<updateUserSettingsUsersMeUpdateSettingsPostResponse>(getUpdateUserSettingsUsersMeUpdateSettingsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      baseSettings,)
  }
);}


/**
 * Set a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to set as a superuser

Returns:
    User: The user that was set as a superuser
 * @summary Set Superuser
 */
export type setSuperuserUsersSetSuperuserUuidPostResponse200 = {
  data: UserResponse
  status: 200
}

export type setSuperuserUsersSetSuperuserUuidPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type setSuperuserUsersSetSuperuserUuidPostResponseSuccess = (setSuperuserUsersSetSuperuserUuidPostResponse200) & {
  headers: Headers;
};
export type setSuperuserUsersSetSuperuserUuidPostResponseError = (setSuperuserUsersSetSuperuserUuidPostResponse422) & {
  headers: Headers;
};

export type setSuperuserUsersSetSuperuserUuidPostResponse = (setSuperuserUsersSetSuperuserUuidPostResponseSuccess | setSuperuserUsersSetSuperuserUuidPostResponseError)

export const getSetSuperuserUsersSetSuperuserUuidPostUrl = (uuid: string,) => {


  

  return `/users/set_superuser/${uuid}`
}

export const setSuperuserUsersSetSuperuserUuidPost = async (uuid: string, options?: RequestInit): Promise<setSuperuserUsersSetSuperuserUuidPostResponse> => {
  
  return customInstance<setSuperuserUsersSetSuperuserUuidPostResponse>(getSetSuperuserUsersSetSuperuserUuidPostUrl(uuid),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * Remove a user as a superuser

Requires superuser access

Parameters:
    uuid (uuid): The uuid of the user to remove as a superuser

Returns:
    User: The user that was removed as a superuser
 * @summary Remove Superuser
 */
export type removeSuperuserUsersRemoveSuperuserUuidPostResponse200 = {
  data: UserResponse
  status: 200
}

export type removeSuperuserUsersRemoveSuperuserUuidPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type removeSuperuserUsersRemoveSuperuserUuidPostResponseSuccess = (removeSuperuserUsersRemoveSuperuserUuidPostResponse200) & {
  headers: Headers;
};
export type removeSuperuserUsersRemoveSuperuserUuidPostResponseError = (removeSuperuserUsersRemoveSuperuserUuidPostResponse422) & {
  headers: Headers;
};

export type removeSuperuserUsersRemoveSuperuserUuidPostResponse = (removeSuperuserUsersRemoveSuperuserUuidPostResponseSuccess | removeSuperuserUsersRemoveSuperuserUuidPostResponseError)

export const getRemoveSuperuserUsersRemoveSuperuserUuidPostUrl = (uuid: string,) => {


  

  return `/users/remove_superuser/${uuid}`
}

export const removeSuperuserUsersRemoveSuperuserUuidPost = async (uuid: string, options?: RequestInit): Promise<removeSuperuserUsersRemoveSuperuserUuidPostResponse> => {
  
  return customInstance<removeSuperuserUsersRemoveSuperuserUuidPostResponse>(getRemoveSuperuserUsersRemoveSuperuserUuidPostUrl(uuid),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * Validate the current user

Returns:
    User: The current user
 * @summary Validate User
 */
export type validateUserAuthValidateGetResponse200 = {
  data: UserResponse
  status: 200
}
    
export type validateUserAuthValidateGetResponseSuccess = (validateUserAuthValidateGetResponse200) & {
  headers: Headers;
};
;

export type validateUserAuthValidateGetResponse = (validateUserAuthValidateGetResponseSuccess)

export const getValidateUserAuthValidateGetUrl = () => {


  

  return `/auth/validate`
}

export const validateUserAuthValidateGet = async ( options?: RequestInit): Promise<validateUserAuthValidateGetResponse> => {
  
  return customInstance<validateUserAuthValidateGetResponse>(getValidateUserAuthValidateGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


