/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.2.0
 */
import * as zod from 'zod';


/**
 * Send a verification code to an email, using an email template

Parameters:
    email (NameEmail): The email to send the verification code to
    code (int): The verification code to send

Returns:
    JSONResponse: A message indicating that the email has been sent
 * @summary Send Verification Code
 */
export const SendVerificationCodeEmailPostQueryParams = zod.object({
  "email": zod.string(),
  "code": zod.number()
})

export const SendVerificationCodeEmailPostResponse = zod.unknown()

