/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: v2.3.0
 */
import * as zod from 'zod';


/**
 * Send a verification code to an email, using an email template
 *
 * Parameters:
 *     email (NameEmail): The email to send the verification code to
 *     code (int): The verification code to send
 *     style (Literal["verification_code", "forgot_password"]): The style of the email
 *
 * Returns:
 *     JSONResponse: A message indicating that the email has been sent
 * @summary Send Verification Code
 */
export const sendVerificationCodeEmailVerificationCodePostQueryStyleDefault = `verification_code`;

export const SendVerificationCodeEmailVerificationCodePostQueryParams = zod.object({
  "email": zod.string(),
  "code": zod.int(),
  "style": zod.enum(['verification_code', 'forgot_password']).default(sendVerificationCodeEmailVerificationCodePostQueryStyleDefault)
})

export const SendVerificationCodeEmailVerificationCodePostResponse = zod.unknown()

/**
 * Send a password change notification to an email
 *
 * Parameters:
 *     email (NameEmail): The email to send the verification code to
 *     code (int): The verification code to send
 *
 * Returns:
 *     JSONResponse: A message indicating that the email has been sent
 * @summary Send Password Change Notification
 */
export const SendPasswordChangeNotificationEmailPasswordChangeNotificationPostQueryParams = zod.object({
  "email": zod.string(),
  "username": zod.string()
})

export const SendPasswordChangeNotificationEmailPasswordChangeNotificationPostResponse = zod.unknown()

